### ISSUE TITLE
Filename length in cache folders

### ISSUE THREAD

**Issue by quai20** [euroargodev/argopy#12]
when querying a certain amount of cycle, and store the result in a cache file :
` argo_loader.profile(6902746, np.arange(12,45)).to_xarray()`

the file created in **tmp/** is too long (on my linux at least) creating a Errno13.

```
Here are some filename length limits in popular file systems:

BTRFS   255 bytes
exFAT   255 UTF-16 characters
ext2    255 bytes
ext3    255 bytes
ext3cow 255 bytes
ext4    255 bytes
FAT32   8.3 (255 UCS-2 code units with VFAT LFNs)
NTFS    255 characters
XFS     255 bytes
```

**Comment by gmaze** [comment]
I guess you used the ``cache`` option to store fetched data.
The name of the cache file depends on the data fetched. So yes for a complex request, like here a lot of cycles, this creates a long file name.
The exact cache name depends on backend, for the erddap you used, the cache file name prefix will be:

```python
file_pref = ArgoDataFetcher(backend='erddap').profile(6902746, np.arange(12,45)).fetcher.cname(cache=1)

print(file_pref)
"phy_WMO6902746_CYC0012_CYC0013_CYC0014_CYC0015_CYC0016_CYC0017_CYC0018_CYC0019_CYC0020_CYC0021_CYC0022_CYC0023_CYC0024_CYC0025_CYC0026_CYC0027_CYC0028_CYC0029_CYC0030_CYC0031_CYC0032_CYC0033_CYC0034_CYC0035_CYC0036_CYC0037_CYC0038_CYC0039_CYC0040_CYC0041_CYC0042_CYC0043_CYC0044"

# len(file_pref) = 278
```
which is indeed way too long !

To fix this, we probably need some file naming that does not depend on the request, with a hash or something like that. 

But then, we need a table lookup to retrieve that file the next time it is requested.

Any idea on how to implement that properly ?
