### ISSUE TITLE
ArgoDataFetcher - 404 error: failure to find ArgoFloats dataset

### ISSUE THREAD

**Issue by scalemailted** [euroargodev/argopy#163]
It appears the REST API for the data fetcher may be down. The following URL does not resolve.

https://www.ifremer.fr/erddap/tabledap/ArgoFloats.html

It produces an error message:

Error {
    code=404;
    message="Not Found: Currently unknown datasetID=ArgoFloats";
}

It appears this URL was working and recorded by wayback machine in 2020-09-23
https://web.archive.org/web/20200923105702/https://www.ifremer.fr/erddap/tabledap/ArgoFloats.html

Is this a problem on my end or is this a problem on the server side?

**Comment by scalemailted** [comment]
Google cached version from Dec 25 2021

https://webcache.googleusercontent.com/search?q=cache:wJF3St1b-kYJ:https://www.ifremer.fr/erddap/tabledap/ArgoFloats.html+&cd=1&hl=en&ct=clnk&gl=us

**Comment by gmaze** [comment]
You can monitor the status of web API used by argopy at: https://argopy.statuspage.io/
and directly in your notebook with:
```python
argopy.status()
```
See https://argopy.readthedocs.io/en/latest/data_sources.html#status-of-sources

**Comment by gmaze** [comment]
@scalemailted , you simply have to wait for the data provider to resume operation of its web API, or try another provider with the ``src`` option of the fetcher

Closing because this does not depends on argopy
