### ISSUE TITLE
Under Sea Ice and SOCCOM Data

### ISSUE THREAD

**Issue by theospira** [euroargodev/argopy#178]
Hi,

I'm using the argopy package to pull some Southern Ocean Argo data and was wondering whether it includes: under sea-ice data as well as SOCCOM data? 
I can't quite figure it out from the supporting documentation.

Thanks,
Theo

**Comment by gmaze** [comment]
Hi @theospira 

## under sea-ice data
Yes, under sea-ice data are available, 
But since the profile position is flagged with QC=8, you need to use the 'expert' mode to fetch such data without filtering QC flags:
```python
from argopy import DataFetcher as ArgoDataFetcher
argo = ArgoDataFetcher(mode='expert').float(7900086)
ds = argo.data
fig, ax = argo.plot()
ax.scatter(ds['LONGITUDE'], ds['LATITUDE'], c=ds['POSITION_QC'])
```
![download (2)](https://user-images.githubusercontent.com/1956032/154062975-fd4469d9-acb7-49d9-b89c-46c1f58e335e.png)

## SOCCOM data
What do you refer to as "SOCCOM data" ? It's a project, so they have their own data. 
But most of their BGC floats data are included into the Argo data stream, hence available with argopy.

Argopy is not yet ready to provide full support for Argo BGC data. 
But using a "localftp" as data source with a "expert" mode, you should be able to get BGC Data:

```python
from argopy import DataFetcher as ArgoDataFetcher
argo = ArgoDataFetcher(src='localftp', ds='bgc', mode='expert').float(5906217)
argo.data
```
<details><summary>List of retrieved variables:</summary>

    CONFIG_MISSION_NUMBER            (N_POINTS) int64 1 1 1 1 1 ... 76 76 76 76
    CYCLE_NUMBER                     (N_POINTS) int64 1 1 1 1 1 ... 76 76 76 76
    DATA_CENTRE                      (N_POINTS) <U2 'AO' 'AO' 'AO' ... 'AO' 'AO'
    DIRECTION                        (N_POINTS) <U1 'A' 'A' 'A' ... 'A' 'A' 'A'
    DOXY                             (N_POINTS) float32 nan nan ... 177.9 181.1
    DOXY_ADJUSTED                    (N_POINTS) float32 nan nan ... 188.1 191.5
    DOXY_ADJUSTED_ERROR              (N_POINTS) float32 nan nan ... 3.097 3.1
    DOXY_ADJUSTED_QC                 (N_POINTS) int64 0 0 0 1 0 1 ... 1 1 1 1 1
    DOXY_QC                          (N_POINTS) int64 0 0 0 3 0 3 ... 3 3 3 3 3
    DOXY_dPRES                       (N_POINTS) float32 nan nan nan ... 0.0 0.0
    FIRMWARE_VERSION                 (N_POINTS) <U32 '081119                 ...
    FLOAT_SERIAL_NO                  (N_POINTS) <U32 '8684                   ...
    NITRATE                          (N_POINTS) float32 nan nan ... 26.93 26.45
    NITRATE_ADJUSTED                 (N_POINTS) float32 nan nan ... 30.28 29.8
    NITRATE_ADJUSTED_ERROR           (N_POINTS) float32 nan nan ... 1.31 1.31
    NITRATE_ADJUSTED_QC              (N_POINTS) int64 0 0 0 1 0 1 ... 1 1 1 1 1
    NITRATE_QC                       (N_POINTS) int64 0 0 0 3 0 3 ... 3 3 3 3 3
    NITRATE_dPRES                    (N_POINTS) float32 nan nan nan ... 0.0 0.0
    PH_IN_SITU_TOTAL                 (N_POINTS) float32 nan nan ... 7.752 7.759
    PH_IN_SITU_TOTAL_ADJUSTED        (N_POINTS) float32 nan nan ... 7.864 7.87
    PH_IN_SITU_TOTAL_ADJUSTED_ERROR  (N_POINTS) float32 nan nan ... 0.01496
    PH_IN_SITU_TOTAL_ADJUSTED_QC     (N_POINTS) int64 0 0 0 1 0 4 ... 4 1 1 1 1
    PH_IN_SITU_TOTAL_QC              (N_POINTS) int64 0 0 0 3 0 4 ... 4 3 3 3 3
    PH_IN_SITU_TOTAL_dPRES           (N_POINTS) float32 nan nan nan ... 0.0 0.0
    PI_NAME                          (N_POINTS) <U64 'STEPHEN RISER, KENNETH ...
    PLATFORM_NUMBER                  (N_POINTS) int64 5906217 ... 5906217
    PLATFORM_TYPE                    (N_POINTS) <U32 'APEX                   ...
    POSITIONING_SYSTEM               (N_POINTS) <U8 'GPS     ' ... 'GPS     '
    POSITION_QC                      (N_POINTS) int64 1 1 1 1 1 1 ... 1 1 1 1 1
    PRES                             (N_POINTS) float32 4.4 6.1 ... 1.999e+03
    PRES_ADJUSTED                    (N_POINTS) float32 4.8 6.4 ... 2e+03
    PRES_ADJUSTED_ERROR              (N_POINTS) float32 2.4 2.4 2.4 ... nan nan
    PRES_ADJUSTED_QC                 (N_POINTS) int64 1 1 1 1 1 1 ... 1 1 1 1 1
    PRES_QC                          (N_POINTS) int64 1 1 1 1 1 1 ... 1 1 1 1 1
    PROFILE_DOXY_QC                  (N_POINTS) object b'A' b'A' ... b'A' b'A'
    PROFILE_NITRATE_QC               (N_POINTS) object b'A' b'A' ... b'A' b'A'
    PROFILE_PH_IN_SITU_TOTAL_QC      (N_POINTS) object b'C' b'C' ... b'B' b'B'
    PROFILE_PRES_QC                  (N_POINTS) <U1 'A' 'A' 'A' ... 'A' 'A' 'A'
    PROFILE_PSAL_QC                  (N_POINTS) <U1 'B' 'B' 'B' ... 'F' 'F' 'F'
    PROFILE_TEMP_QC                  (N_POINTS) <U1 'B' 'B' 'B' ... 'A' 'A' 'A'
    PROJECT_NAME                     (N_POINTS) <U64 'UW, SOCCOM, Argo equiva...
    PSAL                             (N_POINTS) float32 34.12 34.12 ... 34.75
    PSAL_ADJUSTED                    (N_POINTS) float32 34.12 34.12 ... 34.75
    PSAL_ADJUSTED_ERROR              (N_POINTS) float32 0.01 0.01 ... nan nan
    PSAL_ADJUSTED_QC                 (N_POINTS) int64 1 1 1 8 1 8 ... 4 4 4 4 4
    PSAL_QC                          (N_POINTS) int64 1 1 1 8 1 8 ... 4 4 4 4 4
    PSAL_dPRES                       (N_POINTS) float32 0.0 0.0 0.0 ... 0.0 0.0
    TEMP                             (N_POINTS) float32 7.719 7.722 ... 2.572
    TEMP_ADJUSTED                    (N_POINTS) float32 7.719 7.722 ... 2.572
    TEMP_ADJUSTED_ERROR              (N_POINTS) float32 0.002 0.002 ... nan nan
    TEMP_ADJUSTED_QC                 (N_POINTS) int64 1 1 1 8 1 8 ... 1 1 1 1 1
    TEMP_QC                          (N_POINTS) int64 1 1 1 8 1 8 ... 1 1 1 1 1
    TEMP_dPRES                       (N_POINTS) float32 0.0 0.0 0.0 ... 0.0 0.0
    TIME_LOCATION                    (N_POINTS) datetime64[ns] 2019-12-29T16:...
    TIME_QC                          (N_POINTS) int64 1 1 1 1 1 1 ... 1 1 1 1 1
    WMO_INST_TYPE                    (N_POINTS) int64 846 846 846 ... 846 846

</details>

**Comment by gmaze** [comment]
# Important notice !
You should install the last development version of argopy in order to get rid of some bugs avoiding the above to work:
```bash
pip install git+http://github.com/euroargodev/argopy.git@master
```

and you will need the [h5netcdf](https://github.com/h5netcdf/h5netcdf) library in order to read the BGC netcdf files

**Comment by gmaze** [comment]
> I get the following error:

Is your argopy option ``local_ftp`` pointing to a local copy of the Argo GDAC ftp ?

```python
from argopy.options import OPTIONS
argopy.set_options(local_ftp='/Users/gmaze/data/ARGO/ftp_current')
```

**Comment by theospira** [comment]
Hi again @gmaze,

Thanks for all your previous help. I haven't got round to checking the SOCCOM data query as I've hit a different issue with my argo data, and i was hoping you might be able to help with. 

I am trying to convert an argo dataset containing Southern Ocean data from points to profiles:
`ds=ds.argo.point2profile()`
However, since this is a large file (~14GB unpacked, ~8GB when chunked with dask via `xr.open_mfdataset` with N_POINTS=85629290), I have tried to break this dataset up using the following function:

```
def point2profile_func(ds,sections,filepath):
    """
    function that converts an Argo ds from 1D (N_POINTS) to 2D (N_PROF,N_LEVELS) using xr.argo.point2profile().
    Remember to set the filepath and use an integer for sections such that sections|len(ds.N_POINTS).
    AND remember to create folder where individual profile files are saved to, then concat afterwards.
    """
    for i in range(len(os.listdir(r+str(filepath)),sections):
        if i==0:
            slice_0=0
        else:
            slice_0 = np.where(ds.N_POINTS<(len(ds.N_POINTS))*i/sections)[0][-1]
        slice_1 = np.where(ds.N_POINTS<(len(ds.N_POINTS))*(i+1)/sections)[0][-1]
        print("splitting ds "str(i+1)+"/"+str(sections))
        ds=ds.sel(N_POINTS=slice(slice_0,slice_1))
        print("converting points to profiles:")
        ds=ds.argo.point2profile()
        print("saving...")
        ds.to_netcdf(r""+str(filepath)+"Argo_2D_"+str(i+1)+".nc")
        print(str(i+1)+"/"+str(sections)+" saved.")
        del(ds)
```

Even when splitting to smaller sizes, this conversion function is extremely slow and I haven't gained a single file yet. Do you know if there is something I am doing wrong or a faster way to do this? Please see below the variables contained in the dataset.

![image](https://user-images.githubusercontent.com/86719486/159908972-45a1f89c-8a7d-43e8-8b78-15ee6aa2f74c.png)

I am also aware that I might be asking the wrong person, and it could be better to post in xarray issues. Nonetheless, I would be grateful for any help you can provide! 

Thanks,
Theo

**Comment by gmaze** [comment]
Hi @theospira 
I have no idea and I would be very curious to know how you manage to create a dataset with 85 millions of points, can you please tell us more ...

In the mean time, you could try the following snippet codes to transform this into a collection of profiles:

Start a dask cluster:
```python
from dask.distributed import Client

client = Client(n_workers=4)  # Or anything else suitable to your computational resources
```
then apply the point2profile transformation by chunk of float profiles:
```python
from dask import delayed

def func(ds_block):
    out = argopy.xarray.ArgoAccessor(ds_block).point2profile()
    # can't use ds_block.argo accessor here ...
    return out

def merge(ds_list):
    ds = xr.concat(ds_list,
       dim='N_PROF',
       data_vars='minimal',
       coords='minimal',
       compat='override')
    return ds

results = []
for wmo, ds_block in ds.groupby('PLATFORM_NUMBER'):
    y = delayed(func)(ds_block)
    results.append(y)

new_ds = delayed(merge)(results)    
```

**Comment by kelseybisson** [comment]
Hello! I'm chiming in as a user of under ice floats. You can look for the position uncertainty flags in the lat/lon identifiers, then download sea ice concentration data to confirm. I recently worked on an under ice Argo analysis and found a fair amount of 'under ice' suspected profiles that were actually in open water (sea ice concentration of 0% for at least 50km in all directions). The tricky part is that sometimes float positions are interpolated when the float surfaces in open water, so the position can be very uncertain even if lat/lons are provided. If the float doesn't surface before/after the under ice event, there will be no lat/lon data. 

You can also check to see what portion of the vertical water column is present. Floats will descend anywhere from 5-20 meters so avoid the ice due to the ice avoidant algorithm, and that can help identify under ice profiles as well. I recently wrote up my analysis and I'm [pasting in case helpful! ](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021GL095051?casa_token=mGZA4iZYLo0AAAAA%3AdvGTWdeyT-8OiqJN7zG5MbZ2jtfXsmUwD8zdvj0L_zT9w5w-zi39FPC6smqfEQOAD_DgOhgLfO0C )

> 
> Thank you for that information, it's very useful!
> 
> **Under Sea-Ice** My understanding is that QC=8 indicates an estimated time and location when there are data missing. So it is an assumption that it is under sea-ice, and it could be possible that the floats are not transmitting for other reasons (cloud cover, satellites error or other faults) - is that correct?
> 
> **SOCCOM** Great. It was my understanding that SOCCOM is supported by Argo but I couldn't find any documentation on whether the SOCOM data are also included within the Argo dataset. However, running the exact same couple of lines of code for BGC Data, I get the following error:
> 
> ```
> FtpPathError: This path is not GDAC compliant:
> -
> ```

**Comment by apswong** [comment]
Hello @theospira.  I just came across this Github thread and wanted to provide some answers to your questions.

First, what we refer to as "under-ice" profiles is an abbreviated way to refer to profiles taken at times when the ice-avoidance algorithm returned "true" to the specified temperature parameters.  The idea is to stop the float from surfacing when there is "likely" to be sea ice at the surface, so as to reduce the chance of damaging the float.  As @kelseybisson mentioned, the correlation with authentic sea ice coverage is not 100%, as many open water regions around Antarctica have the same low temperatures.

Second, float data from the SOCCOM project are included in the Argo dataset.  In Argo data files, under the variable PROJECT_NAME, you should find entries with char string "UW, SOCCOM, Argo equivalent".

Hope this helps.  - Annie

**Comment by gmaze** [comment]
Closing because this seems to be addressed by responses above.
I add that with the v0.1.14 release, you can fetch BGC data in expert mode, thus including SOCCOM floats
