### ISSUE TITLE
README size and badges

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#188]
I just added one more badge to our [README file](https://github.com/euroargodev/argopy/blob/master/README.md)

We should probably start to split the presentation table, this is like going crazy on the number of badges !

I found all of them useful, but the core information is probably lost and the visual appeal of badges as well

Also we provide a lot of informations that are redundant with the [documentation](https://argopy.readthedocs.io/), I think we could remove most of it and points to the doc

A simpler view could go like:

|<img src="https://raw.githubusercontent.com/euroargodev/argopy/master/docs/_static/argopy_logo_long.png" alt="argopy logo" width="200"/><br>``argopy`` is a python library dedicated to Argo data access, visualisation and manipulation for regular users as well as Argo experts and operators|
|:---------:|
|[![JOSS](https://img.shields.io/badge/DOI-10.21105%2Fjoss.02425-brightgreen)](//dx.doi.org/10.21105/joss.02425) ![CI](https://github.com/euroargodev/argopy/actions/workflows/pytests-free.yml/badge.svg) [![codecov](https://codecov.io/gh/euroargodev/argopy/branch/master/graph/badge.svg)](https://codecov.io/gh/euroargodev/argopy) [![Documentation Status](https://img.shields.io/readthedocs/argopy?logo=readthedocs)](https://argopy.readthedocs.io/en/latest/?badge=latest) [![PyPI](https://img.shields.io/pypi/v/argopy)](//pypi.org/project/argopy/)|

**Comment by quai20** [comment]
<img src="https://user-images.githubusercontent.com/17851004/157411239-8ea4297a-b328-4ff6-87a9-d74fdc8a6f4c.png" width="450" height="300" />
:smiley:   

I agree we can simplify, what you proposed is well enough.

**Comment by gmaze** [comment]
- [ ] I would propose to remove most of the README content and points to the documentation page directly.
This will make info easier to maintain as well.

- [ ] The current table with all badges could be moved to the documentation landing page
