### ISSUE TITLE
Implement data fetcher for the argovis at Colorado Univ. 

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#2]
Folks at the Colorado Univ. developed a nice web interface and webAPI to access Argo data.

More info at: http://www.argo.ucsd.edu/Argovis/Argovis_Tutorials.html

We should be able to provide data fetcher for this access point.

**Comment by tylertucker202** [comment]
I'd love to be a part of this effort!

**Comment by gmaze** [comment]
Hi @tylertucker202 
this would be great
at this point, I was thinking of something working the same way as the other 2 data fetchers, depending on dataset ('core', or 'bgc') retrieve data for a region, a float, a profile with the Argovis

**Comment by gmaze** [comment]
So it would go in https://github.com/euroargodev/argopy/tree/master/argopy/data_fetchers as a argovis.py library

**Comment by gmaze** [comment]
Hi @tylertucker202 
I've just seen this event https://docs.google.com/forms/d/e/1FAIpQLSd31e9pXJGL6nAV4DATlq4nj4Qf7kNNuLa7tu-1Tp1VjxVYkg/viewform
Would it make sense to have the argovis fetcher available before that ?

**Comment by donatagiglio** [comment]
Hi @gmaze, thanks for your suggestion. I will email you to discuss next steps!

**Comment by tylertucker202** [comment]
OK, I cloned the project. data_fetchers has an ArgovisDataFetcher class that uses our API to get dict data. ArgovisDataFetcher also includes a to_dataframe() and to_xarray() methods. I included a test script avtest.py that checks these methods. 

How do we merge? Can we make a branch and allow me access?

Not sure how to integrate this with remaining. This class is much simplar than localftp.py and erddap.py. Many of the boiler plate methods functions aren't needed...

**Comment by quai20** [comment]
Hi @tylertucker202 ,
you can probably save your contributions in a new branch and create a pull request for that branch. From there we'll be able to discuss the modifications and merge. If there is some permissions issues, you can also create the PR from your own fork of argopy.

**Comment by gmaze** [comment]
Hi @tylertucker202 
Great, this is going to be awesome !
Creating a PR from your fork should be the way to proceed as indicated by Kevin 
Then ask a review from @quai20 and @gmaze 
g
