### ISSUE TITLE
Loading multiple floats on Erddap

### ISSUE THREAD

**Issue by RaphaelBajon** [euroargodev/argopy#201]
Issue while loading more than 4 floats (5 or more) with erddap server, in both modes ('expert' or 'standard'). The problem is solved using argovis source. 

```python
import sys, os, glob
import numpy as np
import pandas as pd
import xarray as xr
xr.set_options(display_style="html", display_expand_attrs=False);
import matplotlib.pylab as plt
import matplotlib as mpl
import matplotlib.cm as cm
import seaborn
import argopy

argopy.set_options(mode='expert', src='erddap', dataset='phy')
# or 
#argopy.set_options(mode='standard', src='erddap', dataset='phy')
argo_loader = ArgoDataFetcher().float([6901522, 6901523, 6901601, 6901602, 6901631, 6901750]).load()
```

#### Expected Output

<datafetcher.erddap>
Name: Ifremer erddap Argo data fetcher for floats
API: https://www.ifremer.fr/erddap
Domain: phy;WMO6901522,...,WMO6901750
Backend: erddap
User mode: expert
Dataset: phy

#### Problem Description

Loading more than 4 floats leads to an error. However,  it is working for less than 4 floats included. At the end of the error, I am getting :
TypeError: 'int' object is not iterable 

#### Options

ARGOPY OPTIONS
--------------
api_timeout: 60
cachedir: /Users/rbajon/.cache/argopy
dataset: phy
local_ftp: /Users/rbajon/.argopy_tutorial_data/ftp
mode: expert
src: erddap
trust_env: False 

#### Versions

 INSTALLED VERSIONS
------------------
commit: None
python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:06:49) 
[Clang 12.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 21.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.12.1
libnetcdf: 4.8.1

argopy: 999
xarray: 2022.3.0
scipy: 1.8.0
sklearn: 1.0.2
netCDF4: 1.5.8
dask: 2022.02.1
toolz: 0.11.2
erddapy: 1.2.0
fsspec: 2022.02.0
gsw: 3.4.0
aiohttp: 3.8.1
bottleneck: 1.3.4
cartopy: 0.20.2
cftime: 1.5.2
conda: None
distributed: 2022.2.1
IPython: 8.0.1
iris: None
matplotlib: 3.5.1
nc_time_axis: None
numpy: 1.22.2
pandas: 1.4.1
packaging: 21.3
pip: 22.0.3
PseudoNetCDF: None
pytest: 7.0.1
seaborn: 0.11.2
setuptools: 59.8.0
sphinx: None
zarr: 2.11.0
tqdm: 4.63.0
ipykernel: 6.9.1
ipywidgets: 7.6.5 

</details>

**Comment by gmaze** [comment]
Thanks @RaphaelBajon for pointing this issue
I've found the bug in the erddap data fetcher in here: https://github.com/euroargodev/argopy/blob/e5c55c05fd507354a5114d9c445053c3d84596bf/argopy/data_fetchers/erddap_data.py#L585

I fixed it in https://github.com/euroargodev/argopy/commit/13a180b8b1a656220a0e1cbbdd031b5fe95cb33f

Please update your code with the last master branch, or wait for the next release
