### ISSUE TITLE
😯  length of utilities.py

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#205]
Our utilities module has grown quite large: 2539 lines, 145 functions in the upcoming #157 ...
May be it's time for a refactoring !

**Comment by ocefpaf** [comment]
> Our utilities module has grown quite large: 2539 lines, 145 functions in the upcoming #157 ... May be it's time for a refactoring !

@gmaze would you be interested in mentoring a Google Summer of Code participant on this refactor? If so, please send me a message (email, twitter, whatever works for you). We can probably add argopy as part of IOOS 2023 GSoC application.

**Comment by gmaze** [comment]
Little update: utilities is now 2987 lines !

**Comment by gmaze** [comment]
#290 solved this
