### ISSUE TITLE
create_float_source code generate many nan values in matrix files

### ISSUE THREAD

**Issue by kamwal** [euroargodev/argopy#219]
I have found that the python code to create_source_data is generating many nan values in SAL and TEMP data of WMO matrix .mat. While in netcdf files or in matlab equivalent code to create_source_data are showing much more available numeric data. 

Example float with this issue: 6901967; 6901969

The reduced amount of data will lead to poorer owc estimates.

I am using the argopy v0.1.11 version.

**Comment by gmaze** [comment]
Hi @kamwal 
Like in #218 could you please share files generated with the Matlab code ?

**Comment by kamwal** [comment]
[6901967.zip](https://github.com/euroargodev/argopy/files/8698370/6901967.zip)
The key issue for this example is below around 360 dbar where the python code is generating very sparse data values for PSAL and TEMP. While in Matlab version matrix shows much more available numeric data.
