### ISSUE TITLE
easy access for synthetic files?

### ISSUE THREAD

**Issue by kelseybisson** [euroargodev/argopy#22]
Is there a way to get synthetic files from a lat/lon/time into a batch download? The way I am currently using is to call 'wget' to get the database in my university's server, then I query the files on my personal computer. (wget -r -A Sprof.nc -nH --cut-dirs=4 ftp://ftp.ifremer.fr/ifremer/argo/dac/ -A Sprof.nc). This is messy because I have way more files than I need for my particular purpose.

Ideally I'd like to use your code to download a synthetic float profile for particular locations and times.  could it be a simple addition to the API query? I couldn't find it in my search within the documentation.

**Comment by gmaze** [comment]
Hi @kelseybisson 
The ``localftp`` data source could be used for that.

## Qestion 1:
But in your wget, you don't filter anything (space, time, wmo), so you'd like to retrieve the entire dataset ?

## Question 2:
If you work with Sprof file, in which variables are you interested in ?
I guess BGC ?

**Comment by kelseybisson** [comment]
Hello! I don't want the entire dataset. I'd prefer to get a download for a single profile based on a lat/lon and time (or the collection of profiles that meet the lat/lon time requirement) in a python command line (or by modifying a function). 

I am interested in the full BGC set + temp and salinity. (bbp700, chl, light if available). 
thanks for your help!

**Comment by gmaze** [comment]
Ok, this is possible, but not quite yet entirely
Using the ``localftp`` data source together with the option ``ds='bgc'`` you will be able to load Sprof.nc files.

However !
- this is not yet ready for prime time, and if the netcdf file is not entirely compliant, then errors will be raised.
- at this point, you can only fetch a specific float, not yet a space time domain (this will come very soon)

I think that right now, this will not work for the majority of the files, but it should look like this:

Example:
```python
with argopy.set_options(local_ftp='/Volumes/data/ARGO'):
    loader = ArgoDataFetcher(src='localftp', ds='bgc').float(5903248)
    ds = loader.to_xarray()
```
where the folder ``'/Volumes/data/ARGO'`` points toward my local copy of the GDAC server. [See the documentation here](https://argopy.readthedocs.io/en/latest/data_sources.html#Selecting-a-source).

You can then use the ``files`` property of the loader fetcher to check which netcdf files were loaded:
```
loader.fetcher.files
```

**Comment by gmaze** [comment]
Note that we're focusing on developing `argopy` for the core mission first, and then we will focus on the very needed biogeochemical variables.

**Comment by kelseybisson** [comment]
Thank you so much for your advice! Will you post here when the synthetic float download as f(lat,lon,time) is ready for prime time? My understanding is that right now it's not possible to use `errdap` ?

**Comment by gmaze** [comment]
The erddap has the ``ds='bgc'`` option as well, but only oxygen data are available.

```python
ArgoDataFetcher(src='erddap', ds='bgc').float(5903248).to_xarray()
```

Note that the erddap version of the BGC variable is not yet 100% available, so again, most of the time this will not work !

And yes, I'll post here updates about this asap.

**Comment by kelseybisson** [comment]
Ok! Good to know & thanks so much for your help. This is an awesome tool and I'm looking forward to using it for BGC vars :) I'll stay tuned!

**Comment by dnicholson** [comment]
Kelsey - I've been testing this out a bit and it seems to work pretty well for BGC when using local ftp
```python
argopy.set_options(mode='expert',src='localftp',local_ftp='/path/to/gdac')
argo_loader = ArgoDataFetcher(ds='bgc')
ds = argo_loader.float(wmo).to_xarray()
```
you can use [rsync to download the float of interest](http://www.argodatamgt.org/Access-to-data/Argo-GDAC-synchronization-service). For convenient guis to discover float data, [here](http://fleetmonitoring.euro-argo.eu) and [here](http://argovis.colorado.edu) are good places to start.

**Comment by kelseybisson** [comment]
thank you so much!!! I'm going to give this a try. Sorry for my delay- I did not see the new message until now.

**Comment by kelseybisson** [comment]
Hello! 

I'm chiming in again here because I've been testing out ArgoVis and they have an API for developing an api for downloading synthetic floats (it's being tested but here's a look https://github.com/donatagiglio/Argovis/blob/master/argovis_bgc_python_api.ipynb), in case it's of interest to anyone. 

I've been so appreciative of your help! With others I'm building software to identify matchups with Argo floats across a few satellite platforms (ICESat-2, Sentinel3, MODIS) for easy download and visualization. The overall project is called IcePyx (https://icepyx.readthedocs.io/en/latest/), and we are updating it with tools from ArgoVis and likely ArgoPy as dependencies within our program.

**Comment by tylertucker202** [comment]
I would be willing to work on linking Argovis's BGC API with argopy =). Bear in mind that this BGC 'cherrypicking' feature may not be available to the other data sources (errdap, ftp, local) due to how Argovis stores data (in a curated database) that makes it possible to quickly select BGC data. In any case, this type of selection tool is needed by the community. Thanks for chiming in @kelseybisson!

**Comment by gmaze** [comment]
Hi @kelseybisson,
thanks for your patience, 
Working on BGC data from the local, ftp and erddap is on my plate for November, my plan is to produce a release with this new feature (reliable access to BGC data) before Christmas.
@tylertucker202 if we can roll out this "BGC" release with argovis as well, that would be awesome.

**Comment by gmaze** [comment]
Hi @kelseybisson 
if you're still around, well this took a lot more time that expected, but the synthetic files are now available from the `erddap` data source, just check out the v0.1.14 release in the doc https://argopy.readthedocs.io/
In the mean time, closing this issue since it's address by this last release
