### ISSUE TITLE
No longer able to import argopy

### ISSUE THREAD

**Issue by matdever** [euroargodev/argopy#226]
I receive an error when importing argopy, which is new. Is it an issue with my local machine? 

#### MCVE Code Sample

```python
import argopy

```

#### Problem Description

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-4b11ef5ccf74> in <module>
----> 1 import argopy

/opt/anaconda3/lib/python3.7/site-packages/argopy/__init__.py in <module>
     13 
     14 # Import facades:
---> 15 from .fetchers import ArgoDataFetcher as DataFetcher  # noqa: E402
     16 from .fetchers import ArgoIndexFetcher as IndexFetcher  # noqa: E402
     17 

/opt/anaconda3/lib/python3.7/site-packages/argopy/fetchers.py in <module>
     18 from argopy.options import OPTIONS, _VALIDATORS
     19 from .errors import InvalidFetcherAccessPoint, InvalidFetcher
---> 20 from .utilities import list_available_data_src, list_available_index_src, is_box, is_indexbox, check_wmo
     21 from .plotters import plot_trajectory, bar_plot, open_sat_altim_report
     22 

/opt/anaconda3/lib/python3.7/site-packages/argopy/utilities.py in <module>
     38 
     39 from argopy.options import OPTIONS, set_options
---> 40 from argopy.stores import httpstore
     41 from argopy.errors import (
     42     FtpPathError,

/opt/anaconda3/lib/python3.7/site-packages/argopy/stores/__init__.py in <module>
----> 1 from .argo_index import indexstore, indexfilter_wmo, indexfilter_box
      2 from .filesystems import filestore, httpstore, memorystore
      3 
      4 #
      5 __all__ = (

/opt/anaconda3/lib/python3.7/site-packages/argopy/stores/argo_index.py in <module>
      7 from argopy.errors import DataNotFound
      8 from argopy.options import OPTIONS
----> 9 from .filesystems import filestore, memorystore
     10 
     11 

/opt/anaconda3/lib/python3.7/site-packages/argopy/stores/filesystems.py in <module>
      3 import xarray as xr
      4 import pandas as pd
----> 5 import fsspec
      6 import shutil
      7 import pickle

/opt/anaconda3/lib/python3.7/site-packages/fsspec/__init__.py in <module>
      1 from ._version import get_versions
      2 
----> 3 from .spec import AbstractFileSystem
      4 from .registry import (
      5     get_filesystem_class,

/opt/anaconda3/lib/python3.7/site-packages/fsspec/spec.py in <module>
     72 
     73 try:  # optionally derive from pyarrow's FileSystem, if available
---> 74     import pyarrow as pa
     75 except ImportError:
     76     up = object

/opt/anaconda3/lib/python3.7/site-packages/pyarrow/__init__.py in <module>
     52 
     53 
---> 54 from pyarrow.lib import cpu_count, set_cpu_count
     55 from pyarrow.lib import (null, bool_,
     56                          int8, int16, int32, int64,

/opt/anaconda3/lib/python3.7/site-packages/pyarrow/ipc.pxi in init pyarrow.lib()

AttributeError: type object 'pyarrow.lib.Message' has no attribute '__reduce_cython__'

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

</details>

**Comment by gmaze** [comment]
hi @matdever 
this seems to be linked with a pyarrow version not compatible with argopy (and in fact with fsspec)
could you check that your environment matches the minimal versions from: https://github.com/euroargodev/argopy/blob/master/ci/requirements/py3.7-all-min.yml

**Comment by gmaze** [comment]
Hi @matdever , did you fixed your import issue ?

**Comment by gmaze** [comment]
closing because no news is good news
