### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by WualFabre** [euroargodev/argopy#230]
import argopy
argopy.dashboard(5904797, 12)

Hello , I ran lots codes on your site by using PyCharm but when i run the above code i don't get anything. Then I tried running the same code in Jupyter and it worked. What can I do to run this code in PyCharm, or is it possible to run it somewhere else except Jupyter?

<img width="1206" alt="dashboard" src="https://user-images.githubusercontent.com/87760380/183424384-720963d3-0562-4861-8791-5e1b6f8a5646.png">

**Comment by quai20** [comment]
Hi @WualFabre ,
I'm not familiar with Pycharm, sorry. Don't you have a way to get outputs/exec on iPython ?
That way you can open a notebook in pycharm and maybe get the dashboard.
see [this](https://subscription.packtpub.com/book/web-development/9781783551316/4/ch04lvl1sec24/setting-up-ipython-notebook) for instance.
Hope it helps.

**Comment by gmaze** [comment]
Hi @WualFabre 
Note that if you use the option ``url_only=True``, the function call will return the URL of the dashboard that you can open in your browser
more: https://argopy.readthedocs.io/en/latest/generated/argopy.dashboard.html
