### ISSUE TITLE
Better document data returned in "standard" user mode

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#241]
Following interesting discussions with Argo expert community at the [EARISE final meeting](https://www.euro-argo.eu/News-Meetings/Meetings/Others/Euro-Argo-RISE-Final-Meeting), argopy should **better document data returned in "standard" user mode**. The goal is to be clear about what use can be done of these data, filtered automatically by argopy in "standard" user mode.
I recall that in "standard" user mode, argopy returns data QC-flagged 1 or 2 (i.e. "Good value" or "Probably Good value") and select data in the appropriate variable according to the data mode. Therefore, the returned data are necessarily QC 1  or 2 but may contains both real-time and delayed-mode measurements.

However, following the Argo documentation, **real-time data should not be used for science studies sensitive to small pressure and salinity bias** (e.g. calculations of global ocean heat content or mixed layer depth):

In this case Argo recommends the [following guidelines](https://argo.ucsd.edu/data/data-faq/#RorD):
- Use the quality flags in the Argo data files and data labeled with QC = 1
- Only use delayed-mode data (D files)
- Only use ADJUSTED data variables
- PRES_ADJUSTED_ERROR should be checked and where values are greater than 20db, these data should be rejected

and further read ([here](https://argo.ucsd.edu/data/data-faq/#RorD) and [here](https://argo.ucsd.edu/data/how-to-use-argo-files/)) that:
> If your work is not sensitive to small pressure biases, it is probably acceptable to use “R” files. “R” files should be free from gross errors in position, temperature and pressure.  [...]  In general real-time data should be consistent with ocean climatologies. Monthly climatology tests are performed, along with visual comparisons for profiles that fail the tests. 

It is thus recommended that argopy:
- [x] Improve the documentation with the above elements to better inform users about the data content
- [x] Preserve the ``DATA_MODE`` variable in the standard dataset output
- [x] Implement a new user mode to further filter data to return only the delayed mode data suitable for sensitive science studies, possibly a new ``scientist`` mode.

**Comment by gmaze** [comment]
Tagging @tcarval, @vthierryifr, @BSHbirgit for information

**Comment by BSHbirgit** [comment]
Hi Guillaume

I received the stalled status of this task by email notice. Sorry, I did not follow up earlier. I do recall the discussion at the EArise meeting,
I think the recommendations are sound. Scientist as user mode sound ok, but might be still be a bit vage. Iam not sure how to do better, how about 4scientific_use

**Comment by gmaze** [comment]
Hi @BSHbirgit 
no worries, no urge
what about a ``science`` mode instead of ``scientist`` or ``4scientific_use`` (too verbose) ?

**Comment by BSHbirgit** [comment]
Sciene mode would be good for me. I agree 4scientific_use is a bit too verbose.
