### ISSUE TITLE
List of already existing python and argo libraries / snippets

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#3]
Please list url of the libraries you know, its focus/scope and main features.

We don't want to reinvent or redesigned things.

**Comment by gmaze** [comment]
https://github.com/gmaze/pyargo

Focus on profile history variables

Allows to easily read the history of measurements

**Comment by gmaze** [comment]
https://github.com/euroargodev/argopy-osnet

Focus on rapidly loading in-memory measurements from a local copy of the GDAC ftp.

Allows to retrieve in-memory a list of numpy arrays with curated pressure, temperature and salinity measurements

Allows to retrieve a flat collection of measurements or a collection of profiles interpolated on standard depth levels

**Comment by gmaze** [comment]
https://github.com/pvthinker/argopy

Focus on computing climatological statistics from a local copy of the GDAC ftp

**Comment by gmaze** [comment]
https://github.com/jbusecke/xargofloat

Tools to work with argo float data in xarray

Provide a prototype for an interpolation function for argo floats

**Comment by gmaze** [comment]
https://github.com/castelao/CoTeDe

Focus on data QC

Provide a python implementation of real-time Argo QC tests
(see doc for more)[https://cotede.readthedocs.io/en/latest/qctests.html#argo-incomplete]

**Comment by gmaze** [comment]
https://github.com/IQuOD/AutoQC

Focus on data QC

(list of QC tests)[https://github.com/IQuOD/AutoQC/tree/0e66ce33de7b584c8616bd6a782b8a19814af87c/tests]

**Comment by gmaze** [comment]
https://github.com/quai20/DataViz

Provide notebooks to remind all kind of data analytics or visualisation stuff for Argo index files

**Comment by gmaze** [comment]
https://github.com/biofloat/biofloat

This one has not been updated since several years ...

**Comment by philippemiron** [comment]
Deep and surface trajectories of Argo floats, there's different database but something like YoMaHa would be great! 

http://apdrc.soest.hawaii.edu/projects/yomaha/

**Comment by tylertucker202** [comment]
Convert Argo profiles into python documents, and store them on a MongoDB database. This is how Argovis stores its profiles.

https://github.com/tylertucker202/argo-database

**Comment by adamml** [comment]
A suggestion - once there are a few more resources here, why not make this into an [Awesome List](https://github.com/sindresorhus/awesome).

We've done one for [Erddap resources](https://github.com/IrishMarineInstitute/awesome-erddap), so would be happy to help with set up etc.

**Comment by quai20** [comment]
> A suggestion - once there are a few more resources here, why not make this into an [Awesome List](https://github.com/sindresorhus/awesome).
> 
> We've done one for [Erddap resources](https://github.com/IrishMarineInstitute/awesome-erddap), so would be happy to help with set up etc.

Didn't know about [Awesome List](https://github.com/sindresorhus/awesome), thank you this will be useful to me. You can add [Ifremer erddap](http://www.ifremer.fr/erddap/index.html) deployment in the [Erddap resources](https://github.com/IrishMarineInstitute/awesome-erddap).

**Comment by gmaze** [comment]
> Deep and surface trajectories of Argo floats, there are different databases but something like YoMaHa would be great!
> 
> http://apdrc.soest.hawaii.edu/projects/yomaha/

Hi @philippemiron , thanks for the suggestion, ANDRO is a must have along YoMaHa.
Digging into trajectory data would be great in argopy, we have some demands about that, but still a lot to do before moving on to this (consolidating access to T/S/P and then to BGC profile variables), 
if you want to help in any ways that would get you there much faster !

**Comment by philippemiron** [comment]
> > Deep and surface trajectories of Argo floats, there are different databases but something like YoMaHa would be great!
> > http://apdrc.soest.hawaii.edu/projects/yomaha/
> 
> Hi @philippemiron , thanks for the suggestion, ANDRO is a must have along YoMaHa.
> Digging into trajectory data would be great in argopy, we have some demands about that, but still a lot to do before moving on to this (consolidating access to T/S/P and then to BGC profile variables),
> if you want to help in any ways that would get you there much faster !

I'm interested, I will take a look this week how to include trajectory data sets in argopy.

**Comment by gmaze** [comment]
> Convert Argo profiles into python documents, and store them on a MongoDB database. This is how Argovis stores its profiles.
> 
> https://github.com/tylertucker202/argo-database

Hi @tylertucker202 !
Do you suggest that argopy could have a local data store based on MongoDB ?
This would mean that users getting a sync of the GDAC ftp would need to furthermore manage a local database server ?

**Comment by tylertucker202** [comment]
> > Convert Argo profiles into python documents, and store them on a MongoDB database. This is how Argovis stores its profiles.
> > https://github.com/tylertucker202/argo-database
> 
> Hi @tylertucker202 !
> Do you suggest that argopy could have a local data store based on MongoDB ?
> This would mean that users getting a sync of the GDAC ftp would need to furthermore manage a local database server ?

The Issue asked that we list existing python and argo libraries, I'm only providing what is requested and nothing more. If a few brave souls are interested, there are instructions on how to build a dockerized instance of Argovis [here](https://github.com/tylertucker202/argo-database/blob/master/docs/Argovis%20Docker%20Build%20Instructions.pdf)

**Comment by jbusecke** [comment]
> https://github.com/jbusecke/xargofloat

It seems like the functionality of `xargofloat` is already available in [`def linear_interpolation_remap`]. Id be happy to retire `xargofloat` and point to this repo. Is there a tutorial for interpolation of xarray data, that I could link to?

**Comment by gmaze** [comment]
Hi @jbusecke 
Yes, our interpolator implemented by @quai20 is directly adapted from your use of xarrayutils in xargofloat.
The doc for its usage in argopy is here: https://argopy.readthedocs.io/en/latest/data_manipulation.html#Interpolation-to-standard-levels
The ``ds.argo.interp_std_levels`` covers what xargofloat does and if it doesn't the ``linear_interpolation_remap`` is accessible in argopy.utilities to users
so it's up to you decide if you want to retire xargofloat, if you do, we would be please to have you onboard argopy !

**Comment by jbusecke** [comment]
I just added a note in the [readme](https://github.com/jbusecke/xargofloat). The functionality was defunct anyways. If I work on argo in the future Ill head over here. Thanks for the effort. 

Could you maybe edit the post above with a note that the package is defunct/functionality available here?

**Comment by gmaze** [comment]
## bgcArgoDMQC
I just came across: https://github.com/ArgoCanada/bgcArgoDMQC

The general description is: 
A python library of functions for quality controlling dissolved oxygen data. Heavily based on the SOCCOM BGC Argo QC methods program in matlab, uses either NCEP or World Ocean Atlas data to calculate oxygen gains (Johnson et al. 2015).

**Comment by gmaze** [comment]
## bgcArgoDMQC
I just came across: https://github.com/ArgoCanada/bgcArgoDMQC from @cgrdn and @synapticarbors

The general description is: 
A python library of functions for quality controlling dissolved oxygen data. Heavily based on the SOCCOM BGC Argo QC methods program in matlab, uses either NCEP or World Ocean Atlas data to calculate oxygen gains (Johnson et al. 2015).
