### ISSUE TITLE
Problem accessing data with src ='localftp' in 0.1.4

### ISSUE THREAD

**Issue by dnicholson** [euroargodev/argopy#33]
Hi, I'm not sure if this is a bug or something I am doing wrong...

#### MCVE Code Sample

```python
argopy.set_options(mode='expert',src='localftp',local_ftp='/Users/dnicholson/Documents/gdac1/')
argo_loader = ArgoDataFetcher(ds='phy')
test_wmo = 4903261
ds = argo_loader.float(test_wmo).to_xarray()
ds
```

#### Expected Output

This works fine if I downgrade to 0.1.3. I get a similar error with 0.1.4 both for ds='phy' and for ds='bgc'
#### Problem Description

---------------------------------------------------------------------------
NetCDF4FileNotFoundError                  Traceback (most recent call last)
<ipython-input-3-bfd654953ed2> in <module>
      1 test_wmo = 4903261
----> 2 ds = argo_loader.float(test_wmo).to_xarray()
      3 ds

~/opt/anaconda3/envs/argopy/lib/python3.8/site-packages/argopy/fetchers.py in to_xarray(self, **kwargs)
    214         if self._AccessPoint not in self.valid_access_points:
    215             raise InvalidFetcherAccessPoint(" Initialize an access point (%s) first." % ",".join(self.Fetchers.keys()))
--> 216         xds = self.fetcher.to_xarray(**kwargs)
    217         xds = self.postproccessor(xds)
    218         return xds

~/opt/anaconda3/envs/argopy/lib/python3.8/site-packages/argopy/data_fetchers/localftp_data.py in to_xarray(self, errors, client)
    342         """
    343         # Set internal list of files to load:
--> 344         self.list_argo_files(errors=errors)
    345 
    346         # Load data (will raise an error if no data found):

~/opt/anaconda3/envs/argopy/lib/python3.8/site-packages/argopy/data_fetchers/localftp_data.py in list_argo_files(self, errors)
    436             for wmo in self.WMO:
    437                 if self.CYC is None:
--> 438                     self._list_of_argo_files.append(self._absfilepath(wmo, errors=errors))
    439                 else:
    440                     for cyc in self.CYC:

~/opt/anaconda3/envs/argopy/lib/python3.8/site-packages/argopy/data_fetchers/localftp_data.py in _absfilepath(self, wmo, cyc, errors)
    195         elif len(lst) == 0:
    196             if errors == 'raise':
--> 197                 raise NetCDF4FileNotFoundError(pattern)
    198             else:
    199                 # Otherwise remain silent/ignore

NetCDF4FileNotFoundError: "Couldn't find NetCDF4 file: /Users/dnicholson/Documents/gdac1/dac/*/4903261/4903261_prof.nc"

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09) 
[Clang 9.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 19.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.3

argopy: 0.1.4
xarray: 0.15.1
pandas: 1.0.5
numpy: 1.18.5
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.19.0
distributed: 2.19.0
matplotlib: 3.2.2
cartopy: 0.18.0
seaborn: 0.10.1
numbagg: None
setuptools: 47.3.1.post20200616
pip: 20.1.1
conda: None
pytest: None
IPython: 7.15.0
sphinx: 3.0.3

</details>

**Comment by quai20** [comment]
Hi @dnicholson , it appears argopy doesn't find your float on your. Can you check that a simple 
`ls /Users/dnicholson/Documents/gdac1/dac/*/4903261/4903261_prof.nc` find the file ?

**Comment by dnicholson** [comment]
Thanks for the quick reply @quai20. I tracked down the problem and have it working now.

When I [rsync the gdac](http://www.argodatamgt.org/Access-to-data/Argo-GDAC-synchronization-service) there is no folder named 'dac' that is created. instead the netcdf are located, e.g.,
```
/Users/dnicholson/Documents/gdac1/aoml/4903261/4903261_prof.nc
```
when I added a 'dac' folder and moved individual dac folders into 'dac' it works fine. I'm not sure why it was working for me without issue before I updated from 0.1.3 to 0.1.4.

**Comment by quai20** [comment]
Glad to hear that it works (and that the new release doesn't have (that) bug) :smile:

**Comment by gmaze** [comment]
This is indeed a change that I forget to mention in the doc
The localftp fetcher was indeed working in 0.1.3 directly on the rsync like folder structure (without the "dac" folder)
But in 0.1.4, we added the "region" access point for "localftp", and for that we needed to access the index file, that is at the same level of the "dac" folder on the ftp. So the way "localftp" was changed to include the "dac" level.
That's why you lost your files in 0.1.4
This is indeed a breaking changes that I will document in the What's new section of the doc
Sorry about that @dnicholson 
@quai20 , should we find a way for argopy to check this out safely (we need to be compatible with both the ftp and the rsync services).

**Comment by dnicholson** [comment]
Thanks @gmaze and @quai20 for the assistance! This was an easy fix to make. 0.1.4 works great for core 'phy' floats. There are still issues with bgc that emerged when going from 0.1.3 to 0.1.4 that I think are related to h5netcdf vs. netCDF4. I understand that bgc support is still a work in progress.  I'll try to look into this further and hopefully then can provide some feedback that would be more useful for you.

**Comment by gmaze** [comment]
@dnicholson 
yes, BGC variables is our next step and I also identified issues with the netcdf backend to read files.
Please, raise an issue if you identify something that does not behave as expected.
Thanks for your contribution
g
