### ISSUE TITLE
User experience when a webAPI is not alive ?

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#35]
Today the ``argovis`` webAPI was down.
This resulted in cascading small issues from unit testing to doc failing.

In #34 I implemented a function to test if a webAPI entry point is alive or not.
This is used in unit testing to determine if tests can be run or not.

But what about regular argopy usage ? What to do when a webAPI is not alive to improve user experience ?

For instance, when the ``argovis`` API was not available, a fetch like this:
```python 
ArgoDataFetcher().float(1900857).to_xarray()
```
resulted in a ``FileNotFoundError`` error. 
But this is slightly different, the file/data is there, but the API is not available.

When argopy is loaded, available fetchers are listed by the ``utilities.list_available_data_src()`` and ``utilities.list_available_index_src()`` functions. But this is merely an internal compliance check, no real availability is tested.

When a user loads argopy:
```python
import argopy
```
should we also test the real availability of fetchers relying on webAPI ?

or should we try to catch ``FileNotFoundError`` error and consequently test for the API availability and inform better the error message ?

**Comment by gmaze** [comment]
Should we also consider data source live status badges ?
This is rather common for online services (e.g. [here](https://www.githubstatus.com/))
One can imagine a script running regularly on our server and producing a json like file with webAPI status.

Shields.io provides a nice dynamic method:
``https://img.shields.io/badge/dynamic/json?url=<URL>&label=<LABEL>&query=<$.DATA.SUBDATA>&color=<COLOR>&prefix=<PREFIX>&suffix=<SUFFIX>``

We're already using a static json data file for the daily Argo profile count badge:
![Profile count](https://img.shields.io/endpoint?label=Available%20Argo%20profile%20count%3A&style=social&url=https%3A%2F%2Fmap.argo-france.fr%2Fdata%2FARGOFULL.json)

This could look like this:
![](https://img.shields.io/badge/src--erddap-up-brightgreen) ![](https://img.shields.io/badge/src--argovis-down-red) ![](https://img.shields.io/badge/src--eosc-inactive-lightgrey)

**Comment by tylertucker202** [comment]
Hi @gmaze, we can have ArgoPy 'ping' the database for some small information. One of our daily smoke tests checks if the site is up and running by making the query: 

https://argovis.colorado.edu/selection/overview
It gives some database information such as the number of profiles, last added, DACS included. When making an instance of the fetcher, we can make this query to verify the API is working. Perhaps make this query in the fetcher's __init__() method?

**Comment by gmaze** [comment]
@tylertucker202 
Note that in https://github.com/euroargodev/argopy/commit/fdecbff2fe95baeed8dc886efff34167a7fb6003 I added a new utilities function to check API status here: https://github.com/euroargodev/argopy/blob/5a46a39a3368431c6652608ee7241888802f334f/argopy/utilities.py#L416

It can be used like:
```python
argopy.utilities.isAPIconnected(src='erddap')
```

or 

```python
argopy.utilities.isAPIconnected(src='argovis')
```

These will return True or False if a specific API access point can be reached within a timeout request of 2 secs.
It is used in Unit testing to avoid failing tests just because an API is down.

However, the documentation build will fail if an API is not available because many of the doc notebooks rely on these. I still didn't figured out to address that.

**Comment by tylertucker202** [comment]
Outstanding, although it isn't much overhead I think to check each time the Fetcher is instantiated, checking the status upon loading the module is probably safer.
