### ISSUE TITLE
Bring CANYON-MED to argopy

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#361]
Contemplating to bring CANYON-B to argopy

There is a nice Python code written by @MarineFou and @fricour 
see fork here: https://github.com/euroargodev/CANYON-MED

Few comments:
- no NN library is used, it's all encoded brut force !
- I don't see any big difficulties in bringing this to argopy:
  - a new class/function to make predictions could be added as a ``argopy/related`` sub-module
  - text files with NN weights can easily be added to the ``argopy/static/assets`` folder
  - a new entry to the ``argo`` accessor could make this easy to use, the API could look like this:

```python
from argopy import DataFetcher

ds = DataFetcher(ds='bgc', params='DOXY').float(<WMO>).load().data

ds = ds.argo.canyon_med.predict()  # Shall predict all variables: NO3, PO4, SiOH4, PAT, CT, pHT
ds = ds.argo.canyon_med.predict('NO3')
ds = ds.argo.canyon_med.predict(['NO3', 'PO4'])
```
After this, the xarray dataset would have the predicted variables added !

This could be a first step toward bringing [CANYON-B](https://github.com/HCBScienceProducts/CANYON-B) to argopy as well.

poke: @Sauzede @catsch @HCBScienceProducts

**Comment by gmaze** [comment]
poke: @laurcopp !

**Comment by HCBScienceProducts** [comment]
I think this would be a nice gimmick, but I wouldn't see it as a priority.
First, I'd think, the BGC data access and interactions need to be(come) robust. E.g. I'd prioritize BGC-traj data access (-> think of PPOX_DOXY in air data, or parking drift phase BBP time series) over this.

**Comment by gmaze** [comment]
> I think this would be a nice gimmick, but I wouldn't see it as a priority.

surely not a priority, but a very good use-case to proof-test how we can bring BGC regression methods to argopy.
CANYON-B on target.

> I'd prioritize BGC-traj data access
This was raised recently here (#332 ) and we talked about this in LOV with @Sauzede 
I would need to first understand how these data are being used

**Comment by gmaze** [comment]
@HCBScienceProducts you can make the case for traj files in here:
https://github.com/euroargodev/argopy/discussions/214#discussioncomment-2659566

**Comment by laurcopp** [comment]
Good job @gmaze  ! Thanks a lot
