### ISSUE TITLE
Change in matplotlib settings

### ISSUE THREAD

**Issue by PedroVelez** [euroargodev/argopy#38]
Hi, I have noticed than when I import the argopy fetcher:

`from argopy import DataFetcher as ArgoDataFetcher`

there is a change in the style of the matplotlib plots. It seems that importing the fetcher modify the default settings. 
Probably it is not an issue, but it took me to understand what was going one, and it may have some side effects.

**Comment by gmaze** [comment]
Hi @PedroVelez 
You're right, this is because we import [seaborn](https://seaborn.pydata.org/) which does modify default matplotlib settings.
Is this something you want to change ?

**Comment by PedroVelez** [comment]
Thanks!

No, maybe a warning in the documentacion?, although it seems that has been modified in the newer version of seaborn:

_(Note that in versions of seaborn prior to 0.8, set() was called on import. On later versions, it must be explicitly invoked)._ from  https://seaborn.pydata.org/tutorial/aesthetics.html

for the record, to go back to the default matplotlib settings, this works: `plt.style.use('default')`

**Comment by gmaze** [comment]
right now, we try to load seaborn, and if we can, we issue an ``sns.set_style("dark")``

this is not satisfactory

there is a lot of work to be done on the plotters to consolidate the syntax and make them not affecting the user configuration. 
This can be done using seaborn contexts, I've done this in [pyXpcm](http://github.com/obidam/pyxpcm) (see [here](https://github.com/obidam/pyxpcm/blob/master/pyxpcm/plot.py)] and we'll have to do that in argopy as well.
