### ISSUE TITLE
Profiles/cycles and the second profile

### ISSUE THREAD

**Issue by PedroVelez** [euroargodev/argopy#39]
I have noticed that the documentacion says, in several places, something like:

*for profiles of a given float:*
`ds = argo_loader.profile(6901254, 1).to_xarray()`

I think rather than *profiles* should say *cycle* since if there is a descending profile, the above command would bring the two profiles within the first cycle, the descending and the ascending.  (please sea page 13 of the *Argo Data Management Team. Argo user’s manual. https://doi.org/10.13155/29825*)

Maybe it is a different issue,but I have noticed that for the floats with a second profile, as 6901254, this is N_PROF=2, the above command would only bring the core argo mission profile.  This second profile is described in the variable VERTICAL_SAMPLING_SCHEME ( *Reference table 16: vertical sampling schemes* )

sorry of this is not an issue, and just my lack of python's skills.

**Comment by gmaze** [comment]
Hi @PedroVelez 
Thanks for pointing out these subtleties, this is a key point for experts that we didn't managed yet specifically.

So let me clarify what argopy is doing with this argument:

- With the ``erddap`` data source, the 2nd argument of the ``.profile()`` access point will select the ``cycle_number`` in the database, and give back all profiles within this cycle (ascending, descending)

- With the ``localftp`` data source, the 2nd argument of the ``.profile()`` access point will select the first file matching the``cycle_number``, so, in your example it will work with data from "R6901254_001.nc" and not "R6901254_001D.nc". But "R6901254_001.nc" has two profiles (id 0 and 1), both ascending and somehow this information is lost in the output. This may be a bug, I'll check it

- With the ``argovis`` data source, this will point to ascend profiles only, always.

About the name of the access point, you're also right !
May be, as it works now, the "cycle" word corresponds better to what is fetched.
But changing the name would be a strong backward compatibility break.
**So I propose that before we have an access point really fetching profile (as of N_PROF) and another one for cycles, we keep the existing one.**

**Comment by PedroVelez** [comment]
Thanks @gmaze !

maybe it is not necessary to fix this, since, as you said, it it a subtleties for experts  but maybe it can be described in the documentation. By the way, I tested what happens for the floats with a 0 cycle_

- for 6901254, there is a 001D (descend) and 001 (ascened) profiles, both included when ds = argo_loader.profile(6901254, 1).to_xarray()

- for 6900944, there is a 000D (descend) and 000 (ascened) profiles, only the ascend profile is included when ds = argo_loader.profile(6900944, 1).to_xarray()

Pedro

**Comment by gmaze** [comment]
> About the name of the access point, you're also right !

in fact, not precisely.

the ``profile`` access point indicates that you want to retrieve some specific profiles of a given cycle number that you specify with the option ``cyc``.

So, like ``float``, the ``profile`` access points wants to be free of Argo jargon, which in turn, are meant to be used in options like ``wmo`` or ``cyc``.
