### ISSUE TITLE
Basic description of development workflow

### ISSUE THREAD

**Issue by dhruvbalwada** [euroargodev/argopy#43]
It would be helpful to spell out the development workflow to users that might want to contribute to the code, but are not super familiar with navigating github. I have something similar to https://xmitgcm.readthedocs.io/en/latest/development.html in mind.

**Comment by gmaze** [comment]
hi @dhruvbalwada 
thanks for your review and this good suggestion
We've added a development workflow in the documentation at https://argopy.readthedocs.io/en/latest/contributing.html
g
