### ISSUE TITLE
argovis not respecting region definition

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#48]
It seems that the argovis data source fetcher for a region returns more data than it should

#### Code Sample

Load data:
```python
from argopy import DataFetcher as ArgoDataFetcher
box = [-75, -45, 20, 30, 0, 100, '2011-01', '2011-02']
ds = ArgoDataFetcher(src='argovis').region(box).to_xarray()
```

#### Problem
We would expect all profiles to be inside the box domain, and no profiles outside the boundaries. 

Instead, we see profiles to the north of the domain.

Then plot profile position:
```python
import matplotlib.pyplot as plt
def plot_box(b, ax, c='k', lw=1):
    return ax.plot([b[0], b[1], b[1], b[0], b[0]],[b[2], b[2], b[3], b[3], b[2]], color=c, linewidth=lw)

fig, ax = plt.subplots(ncols=1, nrows=1, dpi=120)
plot_box(box, ax, lw=2)
ax.plot(ds['LONGITUDE'], ds['LATITUDE'], 'k+')    
```

![index](https://user-images.githubusercontent.com/1956032/91456515-a97b2080-e883-11ea-9fb8-b572e407c5ef.png)

**This seems to affect only the latitudinal boundaries**. Nothing along the longitude bounds.

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.19.112+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.6.3

argopy: 0.1.5
xarray: 0.16.0
pandas: 1.1.1
numpy: 1.19.1
scipy: 1.5.2
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.4.0
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.24.0
distributed: 2.24.0
matplotlib: 3.3.1
cartopy: None
seaborn: None
numbagg: None
setuptools: 45.1.0.post20200119
pip: 20.2.2
conda: None
pytest: None
IPython: 7.11.1
sphinx: 3.2.1

</details>

**Comment by gmaze** [comment]
@tylertucker202 any idea ??

**Comment by tylertucker202** [comment]
Hi, @gmaze. Argovis profile position is stored as GeoJSON indexed on a sphere. When a shape query is passed into the database, the shape is a spherical polygon. That means lines between points are great circle distances and will bow upwards in the NH. [Here](https://argovis.colorado.edu/ng/home?mapProj=WM&presRange=%5B0,100%5D&selectionStartDate=2011-01-01&selectionEndDate=2011-02-01&threeDayEndDate=2020-08-25&shapes=%5B%5B%5B20,-75%5D,%5B30,-75%5D,%5B30,-45%5D,%5B20,-45%5D,%5B20,-75%5D%5D%5D&includeRealtime=true&onlyBGC=false&onlyDeep=false&threeDayToggle=false) More on how MongoDB queries GeoJson objects are found [here](https://docs.mongodb.com/manual/tutorial/query-a-2dsphere-index/).

**Comment by gmaze** [comment]
I understand now.
Is there a way to modify this behavior on the server size ?
I'd like to avoid as much as possible to fetch more data than required with argopy

**Comment by gmaze** [comment]
@tylertucker202 I introduced a quick fix in #28 but I still have an issue with the selection:

If I fetch data for a rectangular domain, I don't have the same output than the concatenation of rectangular smaller domains.

This is illustrated with the figure below, in red the domain and fetched data in a single request, in green the sub-domains and their fetched data.
the whole domain is: [-60, 0, 20.0, 60.005, 0.0, 500.0, '2007-01', '2007-03']
with a single request, I have 34469 profiles from 168 floats.
with multiple sub-domain requests, I have 34861 profiles from 170 floats.

![index](https://user-images.githubusercontent.com/1956032/91556811-9de73280-e933-11ea-9932-f5d91c0b589a.png)

the different points can be seen between 20 and 25N.

any idea when this could coming from ?

**Comment by tylertucker202** [comment]
Hi @gmaze. We can make another API that makes box selections.

Argovis uses Spherical polygons to make selections (IE polygons that connect using great circle lengths), which appear curved on a 2d projection. Constant longitude lines are not great circle lengths (except on the equator).

The reason why we are not seeing the green dots is that the box selection is not an actual box on a 2d sphere, strictly speaking.

The new 'box' query will search along Cartesian latitude-longitude coordinates.

**Comment by gmaze** [comment]
> The new 'box' query will search along Cartesian latitude-longitude coordinates.

if you could add a rectangular box selection, that would be great to enforce consistency between the fetchers.

In the mean time, we could also add a polygon access point to make use of the argovis capabilities

**Comment by tylertucker202** [comment]
Agreed. I will write the API today, document it, and let you know when it is live.

**Comment by tylertucker202** [comment]
The API has been added and documented. See [here](https://argovis.colorado.edu/api-docs/#/selection/get_selection_box_profiles) for documentation. Instead of a shape, we are adding two lngLat coordinates. See [example] URL. (https://argovis.colorado.edu/selection/box/profiles/?startDate=2019-05-10&endDate=2019-05-24&llCorner=[-177.5,21]&urCorner=[-105,31]&presRange=[0,10]).

**Comment by gmaze** [comment]
Great, thanks @tylertucker202 
I'll check this out asap and get back to you

**Comment by gmaze** [comment]
the new API request works great and return a proper rectangular selection

but the previous url seems not to work anymore, this [request](https://argovis.colorado.edu/selection/profiles?startDate=2011-01-01T00:00:00Z&endDate=2011-02-01T00:00:00Z&shape=[[[-75,20],[-75,30],[-45,30],[-45,20],[-75,20]]]&presRange=[0,100]) returns an error "Point must be an array or object":
```
https://argovis.colorado.edu/selection/profiles?startDate=2011-01-01T00:00:00Z&endDate=2011-02-01T00:00:00Z&shape=[[[-75,20],[-75,30],[-45,30],[-45,20],[-75,20]]]&presRange=[0,100]
```

**Comment by tylertucker202** [comment]
Outstanding news. You spotted a bug that has been fixed. Thanks for calling it to my attention!
