### ISSUE TITLE
ValueError: Got more bytes so far (>#) than requested (#)

### ISSUE THREAD

**Issue by iuryt** [euroargodev/argopy#51]
I'm trying to Fetch a large area for a long time.

#### MCVE Code Sample

```python
# Your code here
from argopy import DataFetcher as ArgoDataFetcher

fetcher = ArgoDataFetcher()

trange = ('1993-01-01','2015-04-23')
argo_loader = fetcher.region([-30,15,-34,-18,0,2000., *trange])
da = argo_loader.to_xarray()
```

#### Expected Output

Get the `xarray` object for the specified region and time.

#### Problem Description

`ValueError: Got more bytes so far (>#) than requested (#)`. 

I found a reference to this error [here](https://github.com/intake/filesystem_spec/issues/160), but couldn't find a way to pass these arguments using `argopy`.
I couldn't find any reference to this problem related to `argopy` and that's why I thought it would be helpful to post it here.

<details><summary>Traceback</summary>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-167-e08ac0609783> in <module>
      5 trange = ('1993-01-01','2015-04-23')
      6 argo_loader = fetcher.region([-52,-30,-34,-18,0,2000., *trange])
----> 7 argo = argo_loader.to_xarray()

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/argopy/fetchers.py in to_xarray(self, **kwargs)
    214         if self._AccessPoint not in self.valid_access_points:
    215             raise InvalidFetcherAccessPoint(" Initialize an access point (%s) first." % ",".join(self.Fetchers.keys()))
--> 216         xds = self.fetcher.to_xarray(**kwargs)
    217         xds = self.postproccessor(xds)
    218         return xds

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/argopy/data_fetchers/erddap_data.py in to_xarray(self)
    335 
    336         # Download data
--> 337         ds = self.fs.open_dataset(self.url)
    338         ds = ds.rename({'row': 'N_POINTS'})
    339 

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/argopy/stores/fsspec_wrappers.py in open_dataset(self, url, **kwargs)
    249         try:
    250             with self.fs.open(url) as of:
--> 251                 ds = xr.open_dataset(of, **kwargs)
    252             self.register(url)
    253             return ds

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, autoclose, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime, decode_timedelta)
    534                 "with engine='scipy' or 'h5netcdf'"
    535             )
--> 536         engine = _get_engine_from_magic_number(filename_or_obj)
    537         if engine == "scipy":
    538             store = backends.ScipyDataStore(filename_or_obj, **backend_kwargs)

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/xarray/backends/api.py in _get_engine_from_magic_number(filename_or_obj)
    119                 "manager"
    120             )
--> 121         magic_number = filename_or_obj.read(8)
    122         filename_or_obj.seek(0)
    123 

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/fsspec/implementations/http.py in read(self, length)
    276         else:
    277             length = min(self.size - self.loc, length)
--> 278         return super().read(length)
    279 
    280     def _fetch_all(self):

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/fsspec/spec.py in read(self, length)
   1237             # don't even bother calling fetch
   1238             return b""
-> 1239         out = self.cache._fetch(self.loc, self.loc + length)
   1240         self.loc += len(out)
   1241         return out

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/fsspec/caching.py in _fetch(self, start, end)
    337         ):
    338             # First read, or extending both before and after
--> 339             self.cache = self.fetcher(start, bend)
    340             self.start = start
    341         elif start < self.start:

~/programs/anaconda3/envs/py36/lib/python3.6/site-packages/fsspec/implementations/http.py in _fetch_range(self, start, end)
    330                         raise ValueError(
    331                             "Got more bytes so far (>%i) than requested (%i)"
--> 332                             % (cl, end - start)
    333                         )
    334                 else:

ValueError: Got more bytes so far (>5245944) than requested (5242888)
```

</details>

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.14.4.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

argopy: 0.1.4
xarray: 0.16.0
pandas: 1.0.5
numpy: 1.19.1
scipy: 1.5.0
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: 1.2.1
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.21.0
distributed: 2.21.0
matplotlib: 3.2.2
cartopy: 0.17.0
seaborn: 0.10.1
numbagg: None
setuptools: 49.2.0.post20200714
pip: 20.1.1
conda: None
pytest: 6.0.1
IPython: 7.16.1
sphinx: 3.1.2

</details>

**Comment by gmaze** [comment]
Hi @iuryt 
Thanks for raising this here
I also encountered this issue recently when working on #28 but I didn't realized it could happens like this

I also realize that the show_versions() misses the ``erddapy`` and ``fsspec`` packages, can you please give the version of these:
```
import erddapy
print("erddapy", erddapy.__version__)
import fsspec
print("fsspec", fsspec.__version__)
```

**Comment by iuryt** [comment]
I'm glad that this could be somehow useful. 
I read carefully the documentation and couldn't find anything related to this.
Is that any simple way to bypass it?

The versions for erddapy and ffspec are:

erddapy 0.5.3
fsspec 0.7.4

**Comment by gmaze** [comment]
With argopy you can't pass argument to the datastore in order to try ``target_options={"block_size": 0}``.

the pb is that I already tried this possible solution with later argopy versions (in particular with #28 ), but that didn't solved the issue systematically.

also, since your request encompasses a fairly large domain:
- did you systematically encountered this error ?
- did you ever get a 413 error, meaning that your request triggered a too large dataset on the server side ?

**Comment by iuryt** [comment]
With half of the domain, it returns the "too large dataset" error.
What I am trying to do now is to Fetch for each 100m of water column and then try to concatenate the xarray objects after that.

Something like this:
```
fetcher = ArgoDataFetcher()

trange = ('1993-01-01','2015-04-23')
BOX = [-52, -30, -34, -18]

dh = 100
deps = np.arange(0,2000+dh,dh)
argos = []
for di,dj in zip(deps[:-1],deps[1:]):
    print(f'{di:04.0f}-{dj:04.0f}m',end='\r')
    argo_loader = fetcher.region([BOX[0],BOX[1],BOX[2],BOX[3],di,dj, *trange])
    argo = argo_loader.to_xarray()

    argo = argo.assign({'TIME':argo.TIME.dt.round('D')})
    argos.append(argo.argo.point2profile())

# Increasing N_LEVELS for each file
offset = np.hstack([0,np.cumsum([argo.N_LEVELS.size for argo in argos])[:-1]])
for i in range(len(argos)):
    argos[i] = argos[i].assign_coords({'N_LEVELS':argos[i].N_LEVELS+offset[i]})
```

But either `xr.combine_nested(argos,concat_dim='N_LEVELS')`  or `xr.concat(argos,dim='N_LEVELS')` returns `NaN` for `PRES`, and maybe this is not the smartest way to do it.

**Comment by gmaze** [comment]
you should not bother doing this ! 
this is exactly what I'm implementing internally with #28 , split+fetch+merge for large requests

this is not stable, but you can try to install the corresponding version of argopy to manage your large request
this is in the branch: [parallel-requests](https://github.com/euroargodev/argopy/tree/parallel-requests)
and docs at: https://argopy.readthedocs.io/en/parallel-requests/performances.html#Parallel-data-fetching

since your request corresponds to a very large chunk of data, it will be split into more than 1000 smaller requests. So, you should use the 'argovis' data source in this case, since it handles a large nb of requests more easily than the `erddap`
this can go like this:
```python
from argopy import DataFetcher as ArgoDataFetcher
fetcher = ArgoDataFetcher(src='argovis', parallel=True, progress=True)
trange = ('1993-01-01','2015-04-23')
argo_loader = fetcher.region([-30,15,-34,-18,0,2000., *trange])
ds = argo_loader.to_xarray(errors='silent')
```
```
100%|██████████| 1092/1092 [01:04<00:00, 17.04it/s]
CPU times: user 43.5 s, sys: 4.24 s, total: 47.7 s
Wall time: 1min 17s
```
It tooks about 1 min from my laptop at home and corresponds to 260Mb of data ...

Note that this is a work in progress...

**Comment by iuryt** [comment]
That's awesome!
I would love to try that.
Currently, I am running it in an HPC and I only installing packages using `pip` or `conda`. 
Is that an easy way to install this branch?
btw, maybe this is a trivial question, but `argovis` seems not to be available for me:
`InvalidFetcher: Requested data fetcher 'argovis' not available !`

**Comment by gmaze** [comment]
are you sure you have an internet connection from your HPC worker or node ? most of the time you don't, this may explain why you don't have the `argovis` available ...

otherwise to work with this branch is less trivial, you have to download it from github and then points your path to where you downloaded it:

```python
import sys
sys.path.insert(0, "/Users/gmaze/git/github/euroargodev/argopy")
import argopy
print("argopy src:", argopy.__file__)
```
```python
argopy src: /Users/gmaze/git/github/euroargodev/argopy/argopy/__init__.py 
```

**Comment by iuryt** [comment]
Thank you very much!
It worked pretty well!
`100%|██████████| 728/728 [00:36<00:00, 19.93it/s]`

For newbies like me who may pass through this issue. I have a cell in the beginning of my notebook, before importing anything, with the code below:

```
#Changes to parallel-requests branch. It will pobably be unecessary after it merges to master.
import subprocess
remote = "https://github.com/euroargodev/argopy.git"
subprocess.run(f"git clone --single-branch --branch parallel-requests {remote}",shell=True)
sys.path.insert(0,'./argopy/')

import argopy
print("argopy src:", argopy.__file__)
```

Then I added this folder to `.gitignore`.

**Comment by gmaze** [comment]
I close this issue because you fetched your data, but the original error remains
