### ISSUE TITLE
Binder link on README should point to the latest released version, not the master branch

### ISSUE THREAD

**Issue by jpivarski** [euroargodev/argopy#57]
I'm writing this while waiting for the Binder to load.  `:)`

Binder images take a while to build—minutes, maybe 10 minutes for me right now—but previously built images are saved for future users. If the Binder link points to the master branch, then it would require a new image for every push to master, and the probability that a user (like me) is first can be rather high. However, if the link points to the latest stable release, or even just any stable release, then they don't have to be built as often. It's even possible to trigger the Binder build as part of a deployment, like this:

https://github.com/scikit-hep/uproot/blob/master/binder/trigger_binder.sh

which would ensure that _no_ users are first.

I don't know of a good way to keep the link pointing at the _latest_ tag, though. But any release that's good enough to run the notebook will do.

**Comment by gmaze** [comment]
Hi @jpivarski 
Indeed, this is a good point that went under our radar, thanks for your feedback.
We've updated the README to point to the latest release, which is to be considered the most stable and up to date version.
Also I didn't knew that it was possible to trigger the Binder build as part of a deployment, we'll consider this as well.
g

**Comment by gmaze** [comment]
this raised other issues, like a bug with the dashboard function, but hopefully this is fixed.
Following this, I raised another issue to keep discussing on improving user experience with Binder #60
