### ISSUE TITLE
How to manage dependencies versions for unit testing, releases, binder, etc ...

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#63]
I have a lot of difficulties to ensure successful unit testing on github actions, simply because the tests environments is evolving with dependencies new versions, while my local dev environment is rather fixed (i.e. evolves much less frequently than regular builds on github actions).
So unit testing becomes quite difficult because it's not easy to identify errors from code design, vs errors from new version of dependencies (This is happening right now with xarray version 0.16 breaking argopy in several places).

Also @jpivarski pointed (#57) to the need for our binder link to point to the latest release of argopy (instead of the master branch). This implies that we can also control the environment built by binder and points to the need of having a record of the dependencies versions for which a release works.

So, how do we manage these environments ?
1. A "free" env with whatever the last versions of dependencies is available, to be used in unit testing to future proof argopy
2. A "dev" env with a controlled set of dependencies versions, to be used in unit testing
3. A "release" env with a controlled set of dependencies versions, to be used with Binder (and that would also inform users of the expected env one specific release is working with)

How do we make use of conda-lock for all of that ?

I had a look at how xarray is managing this ([eg here](https://github.com/pydata/xarray/tree/master/ci/requirements)): but this is way to complex for me

@ocefpaf as you mentionned on gitter, would you be interested in helping out with this ?

**Comment by quai20** [comment]
In my opinion, it would be simpler to have the same environment for 2 & 3. We release a version of **argopy** with some requirements and we know that it works. We stick to these versions of dependencies for unit testing (maybe with conda-lock like @ocefpaf mentionned). 
And for part 1, we can have another test suite in a "free/dev" env, and when that one fails, we know it's a dedendency problem.

**Comment by ocefpaf** [comment]
> @ocefpaf as you mentionned on gitter, would you be interested in helping out with this ?

Sure. I can help with the conda-lock test. I also agree with @quai20. However, the dependencies of `argopy` are all stable packages and quite reliable, with the exception of `erddapy` which is an amateurish package and quite dangerous to be used downstream ;-p. So maybe the dev and the binder could be pinned but the release one should be "free." Unless you are experiencing problems with it now.

**Comment by gmaze** [comment]
we are indeed experiencing pbs now with the last version of xarray (#66) and the last release of erddapy (#69 )
so, once we'll have fixed these, we will
- [] issue a fully functional new release (v0.1.7), based on all the latest versions of dependencies
- [] lock/pin the current envs for all platform/python versions
- [] then proceed to use these pins for binder (which will use the last release) and for our ongoing dev.

**Comment by gmaze** [comment]
> with the exception of `erddapy` which is an amateurish package and quite dangerous to be used downstream ;-p

I'm now afraid that `argopy` is not "pro" enough ;-)

**Comment by gmaze** [comment]
When fixing xarray 0.16.1 stuff at #65 , I also tried to implement the use of a "controlled" environment for unit testings, with a "free" env as well (but not failing the overall tests suite on github actions). 

The "controlled" environment is defined with a conda file under ``ci/requirements/py**-dev.yml``. 
It contains the exact env to run argopy for python versions 3.6, 3.7 and 3.8 in dev mode, i.e. it imposes the version of all requirements.

The "free" environment is defined with a conda file under ``ci/requirements/py**-free.yml``.
It contains the list of packages without constrains on versions.

Conda environment are all named "argopy-tests" and are used in the workflow file ``.github/workflows/pythontests.yml``.

When a push or pull request is triggered, the Github Action jobs appear like this:

<img width="262" alt="Screenshot 2020-11-11 at 21 16 52" src="https://user-images.githubusercontent.com/1956032/98859966-40a74b80-2463-11eb-9bc3-b02beab6a734.png">

**Comment by gmaze** [comment]
In the comment above we see that tests ran with the "free" environment are failing.

The exercise of creating ``ci/requirements/py**-dev.yml`` files allowed me to identify one more source of tests error: a filenotfound error raised when testing cache features. 

I determined that with fsspec [0.8.3](https://filesystem-spec.readthedocs.io/en/latest/changelog.html#version-0-8-3), tests pass, but fail with fsspec [0.8.4](https://filesystem-spec.readthedocs.io/en/latest/changelog.html#version-0-8-4). 

It is still not clear however, which exact fsspec changes in these versions trigger the error.
But it explains why the "free" environment tests (installing fsspec 0.8.4) are failing.

**Comment by gmaze** [comment]
I also added a specific environment for the documentation on RTD, it's at ``ci/requirements/doc.yml``

**Comment by quai20** [comment]
Hi there, 
From what I saw in the code & failing tests, `fsspec 0.8.4` is a problem when trying to cache an erddap request. Even if we make a release, I think it will be compatible with `fsspec 0.8.5` (:crossed_fingers:). We could maybe raise something in the `fsspec0.8.4+erddap+caching` case ?
There's also the `fs.cached_file` that doesn't contain the protocol anymore, but that we can fix in argopy to consider both cases.

**Comment by gmaze** [comment]
> I think it will be compatible with `fsspec 0.8.5` (🤞)

May be we can implement unit testing with the master version of critical depedencies (xarray, fsspec, erddapy) to ensure that indeed, argopy is compatible with upcoming releases

**Comment by gmaze** [comment]
> We could maybe raise something in the `fsspec0.8.4+erddap+caching` case ?

A temporary solution would be to raise a warning in this situation and to fall back on NOT caching ?

Not sure how to implement this, probably a test at the instantiation of the filesystem around https://github.com/euroargodev/argopy/blob/464ab42fd14a26f5bebe5344660ce3070a85a638/argopy/stores/filesystems.py#L78

goog idea @quai20 , I'll try this this morning

**Comment by ocefpaf** [comment]
My workflow is mostly Release Early, Release Often (RERO) I'd release with a tight pin on fssec and then, as soon as we can test with latest fsspec, release again with a fix and looser pin.

**Comment by gmaze** [comment]
@ocefpaf thanks for the advice
I also think that I should have released a long time ago

Also the solution above is not that easy to implement without too much patches to the code

So let's proceed to a Christmas release !
