### ISSUE TITLE
test against xarray master

### ISSUE THREAD

**Issue by dcherian** [euroargodev/argopy#66]
It would be a good idea to test against the git master versions of all dependencies, especially xarray. This would've caught #65 early, and helps the xarray team fix things before release.

PS: I love argopy!

**Comment by gmaze** [comment]
Hi @dcherian 

Is this not too similar to the idea of testing with 
> a "free" env with whatever the last versions of dependencies is available, to be used in unit testing to future proof argopy

as mentioned in #63 ?

I am worried than this would take us a lot of efforts, not mentioning the fact that the "master" branch may not be stable and could go back and forth with some dependencies features.

So, true that this may help to detect bugs in dependencies, but I don't think we have the man power, i.e. a dev community on argopy, large enough to sustain this approach

Beside, argopy users mostly relies on properly released dependencies, I think sustaining the "free" env approach will cover a lot of bad user experience

So, to make it short: in a perfect world, this would be a great think to do, but in practice I think we can't afford it (especially with the long list of new features we still have to code to release a prime time ready stable version 1)

**Comment by gmaze** [comment]
we choose to give a try to a "free" environment for unit testing based on the last release of dependencies.
this could be revised later if necessary.
