### ISSUE TITLE
ValueError: Cannot seek strteaming HTTP file

### ISSUE THREAD

**Issue by mayursapkal** [euroargodev/argopy#68]
After successful installation of Argopy, I tried to fetch the data using the code given in  " https://argopy.readthedocs.io/en/latest/data_fetching.html " ,while fetching data I am consistently getting " ValueError: Cannot seek strteaming HTTP file " 

```python
# Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from argopy import DataFetcher as ArgoDataFetcher
>>> argo_loader = ArgoDataFetcher()
>>> argo_loader
<datafetcher 'Not initialised'>
Backend: erddap
Fetchers: profile, float, region
User mode: standard
>>> ds = argo_loader.region([-75, -45, 20, 30, 0, 10, '2011-01-01', '2011-06']).to_xarray()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mayur/anaconda3/lib/python3.8/site-packages/argopy/fetchers.py", line 222, in to_xarray
    xds = self.fetcher.to_xarray(**kwargs)
  File "/home/mayur/anaconda3/lib/python3.8/site-packages/argopy/data_fetchers/erddap_data.py", line 321, in to_xarray
    ds = self.fs.open_dataset(self.url)
  File "/home/mayur/anaconda3/lib/python3.8/site-packages/argopy/stores/fsspec_wrappers.py", line 253, in open_dataset
    ds = xr.open_dataset(of, **kwargs)
  File "/home/mayur/anaconda3/lib/python3.8/site-packages/xarray/backends/api.py", line 529, in open_dataset
    engine = _get_engine_from_magic_number(filename_or_obj)
  File "/home/mayur/anaconda3/lib/python3.8/site-packages/xarray/backends/api.py", line 124, in _get_engine_from_magic_number
    filename_or_obj.seek(0)
  File "/home/mayur/anaconda3/lib/python3.8/site-packages/fsspec/implementations/http.py", line 440, in seek
    raise ValueError("Cannot seek strteaming HTTP file")
ValueError: Cannot seek strteaming HTTP file
>>> 

```

#### Versions

commit: None
python: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-52-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.7.3

argopy: 0.1.6
xarray: 0.16.1
pandas: 1.1.3
numpy: 1.19.1
scipy: 1.5.2
netCDF4: 1.5.3
pydap: installed
h5netcdf: 0.8.1
h5py: 2.10.0
Nio: None
zarr: 2.5.0
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: installed
rasterio: 1.1.7
cfgrib: None
iris: 2.4.0
bottleneck: 1.3.2
dask: 2.30.0
distributed: 2.30.0
matplotlib: 3.3.1
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: installed
setuptools: 50.3.0.post20201006
pip: 20.2.3
conda: 4.9.0
pytest: 6.1.1
IPython: 7.18.1
sphinx: 3.2.1
![20201022_234005](https://user-images.githubusercontent.com/72465799/96912415-f5cb9100-14bf-11eb-8f8e-17935369c704.png)

</details>

**Comment by quai20** [comment]
Hi @mayursapkal !

There are indeed some versionning issues if you use the last versions of **xarray** and **fsspec**, so I would advise not to go higher than `fsspec 0.8.0` and `xarray 0.16.0`, and installing the master version of argopy

```
pip uninstall argopy
pip install git+http://github.com/euroargodev/argopy.git@master
```

**Comment by mayursapkal** [comment]
> Hi @mayursapkal !
> 
> There are indeed some versionning issues if you use the last versions of **xarray** and **fsspec**, so I would advise not to go higher than `fsspec 0.8.0` and `xarray 0.16.0`, and installing the master version of argopy
> 
> ```
> pip uninstall argopy
> pip install git+http://github.com/euroargodev/argopy.git@master
> ```
> 

Hi @quai20 
Thanks for reply 🙌...
I will try this tonight and will update you soon....

**Comment by mayursapkal** [comment]
> > Hi @mayursapkal !
> > 
> > There are indeed some versionning issues if you use the last versions of **xarray** and **fsspec**, so I would advise not to go higher than `fsspec 0.8.0` and `xarray 0.16.0`, and installing the master version of argopy
> > 
> > ```
> > pip uninstall argopy
> > pip install git+http://github.com/euroargodev/argopy.git@master
> > ```
> > 
> 
> Hi @quai20 
> Thanks for reply 🙌...
> I will try this tonight and will update you soon....

Hello @quai20 ...!
Today I tried above given commands and they worked...error resolved..✌️...
Thanks a lot...!
