### ISSUE TITLE
erddapy update to v0.8.0 breaking argopy functionality

### ISSUE THREAD

**Issue by zxcvbnmike15** [euroargodev/argopy#70]
```erddapy``` updated to v0.8.0 which includes a major refactor that removes the utilities module (#145, #148). This breaks the import of argopy.

#### MCVE Code Sample

```python
from argopy import DataFetcher as ArgoDataFetcher

```

#### Expected Output
No expected output.  Should import module without error.

#### Problem Description
Setting up the environment, erddapy is restricted to ```erddapy>=0.6``` . This results in conda installing ```erddapy=0.8.0```. Version 0.8.0 features a major refactor, removing the utilities module. This causes the import error in argopy. This was a very recent change (3 days ago). Downgrading erddapy to version 0.7.0 restores normal functionality.

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:22:52) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252
libhdf5: 1.10.6
libnetcdf: 4.7.4
argopy: 0.1.6
xarray: 0.15.1
pandas: 1.1.4
numpy: 1.19.4
scipy: 1.5.3
fsspec: 0.8.4
erddapy: 0.8.0
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.30.0
distributed: 2.30.1
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
gsw: 3.4.0
setuptools: 49.6.0.post20201009
pip: 20.2.4
conda: None
pytest: 6.1.2
IPython: 7.19.0
sphinx: 3.3.0

</details>

**Comment by gmaze** [comment]
hi @zxcvbnmike15 
thanks for reporting this issue
we also noticed this and are working on a fix at #69 
g
