### ISSUE TITLE
cannot fetch data

### ISSUE THREAD

**Issue by apatlpo** [euroargodev/argopy#79]
```python
from argopy import DataFetcher as ArgoDataFetcher
ds = ArgoDataFetcher(src='erddap').region([-75, -45, 20, 30, 0, 100, '2011-01', '2011-02']).to_xarray()
```

leads to:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-342a12ae1e91> in <module>
----> 1 ds = ArgoDataFetcher(src='erddap').region([-75, -45, 20, 30, 0, 100, '2011-01', '2011-02']).to_xarray()

~/.miniconda3/envs/cognac/lib/python3.8/site-packages/argopy/fetchers.py in to_xarray(self, **kwargs)
    270             raise InvalidFetcher(" Initialize an access point (%s) first." %
    271                                  ",".join(self.Fetchers.keys()))
--> 272         xds = self.fetcher.to_xarray(**kwargs)
    273         xds = self.postproccessor(xds)
    274         return xds

~/.miniconda3/envs/cognac/lib/python3.8/site-packages/argopy/data_fetchers/erddap_data.py in to_xarray(self, errors)
    423         if not self.parallel:
    424             if len(self.uri) == 1:
--> 425                 ds = self.fs.open_dataset(self.uri[0])
    426             else:
    427                 ds = self.fs.open_mfdataset(

~/.miniconda3/envs/cognac/lib/python3.8/site-packages/argopy/stores/filesystems.py in open_dataset(self, url, *args, **kwargs)
    465         #with self.fs.open(url) as of:
    466         #    ds = xr.open_dataset(of, *args, **kwargs)
--> 467         data = self.fs.cat_file(url)
    468         ds = xr.open_dataset(data, *args, **kwargs)
    469         if "source" not in ds.encoding:

AttributeError: 'HTTPFileSystem' object has no attribute 'cat_file'
```

Reversing to this code fixes the issue:

```
with self.fs.open(url) as of:
        ds = xr.open_dataset(of, *args, **kwargs)
```

even though I run into other errors that will be reported later on.

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 | packaged by conda-forge | (default, Jul 24 2020, 01:06:20) 
[Clang 10.0.1 ]
python-bits: 64
OS: Darwin
OS-release: 18.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: None.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

argopy: 0.1.7
xarray: 0.16.0
pandas: 1.0.5
numpy: 1.19.1
scipy: 1.5.2
fsspec: 0.7.4
erddapy: 0.9.0
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.5
cfgrib: None
iris: None
bottleneck: None
dask: 2.20.0
distributed: 2.20.0
matplotlib: 3.2.2
cartopy: 0.18.0
seaborn: None
numbagg: None
gsw: 3.3.1
setuptools: 49.2.0.post20200712
pip: 20.1.1
conda: 4.8.3
pytest: 5.4.3
IPython: 7.16.1
sphinx: None
</details>

**Comment by apatlpo** [comment]
bisecting ffspec indicates you need to bump up the requirement to version 0.8.0 (instead of 0.7.4)

**Comment by gmaze** [comment]
Hi @apatlpo 
This will be updated in the next release, ffspec has implemented a lot of changes recently, this broke a lot of things
Should be fine with ffspec 0.8.3
