### ISSUE TITLE
Visualization/plot API design

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argopy#8]
Dear colleagues,

Since data and meta data fetchers are on track (eg: https://github.com/euroargodev/argopy/pull/6, https://github.com/euroargodev/argopy/pull/5), we very soon gonna need an API for visualization and plotting of fetched Argo information.

This issue is meant to design that API. 
If you want to contribute or shoot some ideas or requests please reply below.
Be specific about the fetched object to be used.

Example:

Plotting **meta-data** object (https://github.com/euroargodev/argopy/pull/6):
```python
from argopy import ArgoIndexFetcher
idx = ArgoIndexFetcher.region([-75, -65, 10, 20]).to_dataframe()

idx.argopy.plot.trajectories() # Create a map with all float trajectories
idx.argopy.plot.dac() # Create a histogram of nb of floats by DAC
idx.argopy.plot.datamode(x='time') # Create a histogram of Data Mode ('R','D','A') over time
```
Note that here the API is ``ds.argopy.plot.<>`` because idx is a [Pandas dataframe that already come with a ``plot`` method](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.plot.html), so we can't customize ``idx.plot.<>``.

Plotting **data** object (eg: https://github.com/euroargodev/argopy/pull/5):
```python
from argopy import ArgoDataFetcher
ds = ArgoDataFetcher.region([-75, -65, 10, 20]).to_xarray()

ds.argopy.plot.trajectories() # Create a map with all float trajectories
ds.argopy.plot.profiles() # Create a plot with superimposed vertical profiles
ds.argopy.plot.profiles(hue='time') # Create a plot with superimposed vertical profiles, colored by time
ds.argopy.plot.tsdiagram() # Create a T/S diagram 
ds['TEMP'].argopy.plot.profiles(hue='QC') # Create a plot of Temperature profiles colored by QC flags

ds = ArgoDataFetcher.float(6902746).to_xarray()
ds.argopy.plot.waterfall(x='TEMP') # Create a water fall plot of temperature
```
Note that here the API is ``ds.argopy.plot.<>`` because ds is a [xarray dataset that already come with a ``plot`` method](http://xarray.pydata.org/en/stable/plotting.html), so we can't customize ``ds.plot.<>``.

**Comment by quai20** [comment]
> Note that here the API is `ds.argopy.plot.<>` because idx is a [Pandas dataframe that already come with a `plot` method](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.plot.html), so we can't customize `idx.plot.<>`.

Maybe _idx_ should'nt be directly the dataframe but an argo index object. **idx.index()** would return the dataframe. Then we could set our own **idx.plot()**

**Comment by gmaze** [comment]
Not comfortable with the idea that idx.index() would return a dataframe, not explicit enough ?

What about moving up level the plot module access ? like this:
```python
from argopy import ArgoIndexFetcher
idx = ArgoIndexFetcher.region([-75, -65, 10, 20])

idx.plot.trajectories()

idx.to_dataframe()
idx.to_csv()

```
then may be *fetcher* is not the most appropriate word for exploring the index, may be simply:

```python
from argopy import ArgoIndex
idx = ArgoIndex.region([-75, -65, 10, 20])
idx.plot.trajectories()
idx.to_dataframe()
idx.to_csv()
```

**Comment by PedroVelez** [comment]
sorry for getting into the topic without the proper language. @gmaze when you said  'visualization and plotting of fetched Argo information.', you ment using matplotlib or seaborn internally to define the method  > ds.argopy.plot.<> ?

**Comment by gmaze** [comment]
yes @PedroVelez i think it would be nice to have a minimum set of plotting functionalities to help get started the standard users, but also more specific plots for Argo experts.

**Comment by gmaze** [comment]
Thanks @rabernat for this comment

I think you're right, this is a very good point, and **we should be focusing on doing one thing right and well.**

Providing a good documentation with a lot of plotting examples is indeed, what we gonna do first (https://github.com/euroargodev/argopy/pull/13), basically building on notebooks from:
https://github.com/euroargodev/erddap_usecases/tree/master/examples

Yet, I can't get help myself but think that 3 to 4 specific plots could be helpful for a quick-and-dirty 1st look at the data. In a sense, this is pretty much like the way I'm using the plot functionalities of xarray: very nice and enough to look at the data, but may need specific plot coding for paper-quality figures (no offense here to the amazing plotting functionalities of xarray)

So the question may be more about `expert` users and even `operators` who use very specific technical plots. Should we have these implemented, here, or even in a companion library.

**Comment by quai20** [comment]
I agree with @gmaze , I like having some basic quick embedded `plot()` functions. But I never use these (in xarray for example), to do my analysis plots. BTW I always end up using matplotlib...

**Comment by rabernat** [comment]
But if all your functions return pandas dataframes or xarray datasets, don’t you *already* have quick embedded plotting functions, via those libraries?

**Comment by gmaze** [comment]
you're right @rabernat 
I think that what I have in mind is that we very often have to combine multiple variables for quite easy plots for experts, like for instance this one:
![QCimage](https://user-images.githubusercontent.com/1956032/78570653-8b097f80-7825-11ea-819a-dda0dd872e1a.png)
that is easy to look at but not straightforward to generate.

We'll see in practice and with user feedbacks how this turns out, but surely, how priority is data mining/ data fetching.

**Comment by gmaze** [comment]
#56 will provide a simple way for histogram and trajectory plots for index and data fetchers.
A visualisation gallery will also be created at: https://argopy.readthedocs.io/en/latest/visualisation.html
