### ISSUE TITLE
feature request: teos sound_speed

### ISSUE THREAD

**Issue by apatlpo** [euroargodev/argopy#80]
issue subject should be pretty explicit

**Comment by gmaze** [comment]
'sounds' like a good idea, will PR this asap ...

**Comment by gmaze** [comment]
@apatlpo what would be the name for this variable to add in the xarray dataset as a new variable ?
C ?

**Comment by gmaze** [comment]
seems like "CS" would be appropriate

**Comment by apatlpo** [comment]
why not follow gsw with the explicit formulation `sound_speed` ? 

You're the boss, anyway ;)
thx for adding this

**Comment by gmaze** [comment]
I'm happy with "SOUND_SPEED" to please users !
should be on master branch today
cheers

**Comment by apatlpo** [comment]
thx !
