### ISSUE TITLE
Accept numpy.int32 as wmo input type

### ISSUE THREAD

**Issue by cgrdn** [euroargodev/argopy#83]
Ran into this trying to grab some float information while looping through some WMO numbers. The following error is thrown

```python
ValueError: WMO must be a list of integers
```

Another less important note: the error states that WMO must be a list of integers, but a single integer (not in a list) is also ok, so this message could be improved.

#### MCVE Code Sample

```python
from argopy import DataFetcher as ArgoDataFetcher
argo_loader = ArgoDataFetcher()

WMOs = np.array([4902553, 4902554, 4902555])
cycles= np.array([2, 3, 6])
print(type(WMOs[0])) # numpy.int32 

for f, c in zip(WMOs, cycles):
    ds = argo_loader.profile(f, cyc).to_xarray() # throws an error
    ds = argo_loader.profile(int(f), cyc).to_xarray() # does not
```

#### Expected Output
Same dataset as second line in for loop, improved error message, perhaps:

```python
ValueError: WMO must be an integer or a list of integers
```

#### Problem Description

User should not need to concern themselves with what kind of integer an integer is. 

#### Versions

<details><summary>INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252
libhdf5: 1.10.4
libnetcdf: 4.7.3

argopy: 0.1.7
xarray: 0.16.1
pandas: 1.1.1
numpy: 1.19.1
scipy: 1.5.0
fsspec: 0.8.0
erddapy: 0.6.0
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.27.0
distributed: 2.27.0
matplotlib: 3.3.1
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: None
gsw: 3.3.1
setuptools: 49.6.0.post20200814
pip: 20.2.2
conda: 4.9.2
pytest: 6.0.2
IPython: 7.18.1
sphinx: 3.2.1</summary>
</details>

**Comment by gmaze** [comment]
Thanks @cgrdn for reporting this
This indeed an issue, working on it at #92
