### ISSUE TITLE
translate HTTP errors for users

### ISSUE THREAD

**Issue by dcherian** [euroargodev/argopy#85]
Thanks for this package. It is very helpful and convenient!

#### MCVE Code Sample

```python
from argopy import DataFetcher as ArgoDataFetcher
argo_loader = ArgoDataFetcher()
ds = argo_loader.region([-145, -135, -2, 8, 0, 500, "2016-01-01", "2020-12-31"]).to_xarray()

```

#### Expected Output

Nice error message saying the request is too big.

#### Problem Description
Current error message is  hard to interpret

```
ClientResponseError: 413, message='413', url=URL(
```

I googled the error code and realized that I should request a smaller subset.

**Comment by ocefpaf** [comment]
I'm not sure at what depth argopy is using erddapy here but [we implemented that recently](https://github.com/ioos/erddapy/blob/9653982fbfabbf6b9310ec356bcfa65519564291/erddapy/url_handling.py#L20) and maybe something similar could be ported to argopy or, just use it directly if the request reaches that part of the code. ERDDAP servers have some nice and informative error messages!

**Comment by gmaze** [comment]
Hi @dcherian 
Thanks for pointing this issue, indeed, we need to report better erddap errors.
However @ocefpaf  we only use erddapy to manage constraints and urls formatting, all http request are managed through fsspec

Note also @dcherian that your request can be handled by argopy with the 'parallel' option documented here: https://argopy.readthedocs.io/en/latest/performances.html#Parallel-data-fetching

```python
argo_loader = ArgoDataFetcher(parallel=True, progress=True)
ds = argo_loader.region([-145, -135, -2, 8, 0, 500, "2016-01-01", "2020-12-31"]).to_xarray()
```
