### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by iuryt** [euroargodev/argopy#86]
I am simply trying to run one of the examples from Usage (https://argopy.readthedocs.io/en/latest/usage.html),
and it returns error.

#### MCVE Code Sample

```python
# Your code here
from argopy import DataFetcher as ArgoDataFetcher
ds = ArgoDataFetcher().region([-75, -45, 20, 30, 0, 100, '2011', '2012']).to_xarray()
```

#### Expected Output
The same from tutorial.

#### Problem Description

It returns
```
FileNotFoundError: https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude>=-75&longitude<=-45&latitude>=20&latitude<=30&pres>=0&pres<=100&time>=1293840000.0&time<=1325376000.0&distinct()&orderBy("time,pres")
```

I tried both with Python 3.6 and 3.9. 
My `.condarc` is:
```
channel_priority: strict
channels:
  - conda-forge

```

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.12 | packaged by conda-forge | (default, Dec  9 2020, 00:36:02) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 2.6.32-754.35.1.el6.x86_64
machine: x86_64
processor: 
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.6.3

argopy: 0.1.7
xarray: 0.16.1
pandas: 1.1.4
numpy: 1.19.5
scipy: 1.2.0
fsspec: 0.8.3
erddapy: 1.0.0
netCDF4: 1.5.4
pydap: None
h5netcdf: 0.8.1
h5py: 3.1.0
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2021.01.1
distributed: 2021.01.1
matplotlib: 3.2.2
cartopy: 0.18.0
seaborn: 0.11.1
numbagg: None
gsw: 3.4.0
setuptools: 49.6.0.post20210108
pip: 21.0
conda: None
pytest: None
IPython: 7.16.1
sphinx: None
</details>

**Comment by quai20** [comment]
Hi @iuryt !
Indeed, Ifremre Erddap server seems to be down at the moment. You can try again later, or you can play with the other data proxy and try to switch to 'argovis' for example : 
`ds = ArgoDataFetcher(src='argovis').region([-75, -45, 20, 30, 0, 100, '2011', '2012']).to_xarray()`
and see if it works.
cheers

**Comment by iuryt** [comment]
Thanks!
I was about to get crazy creating different environments with different versions.
I wonder if we could add a server check on import, or as a method. 
FileNotFoundError seems not appropriate for this case, but if user knew that the server is down by importing..

**Comment by quai20** [comment]
I'm closing the issue but I keep note for the error.
