### ISSUE TITLE
Issues with DataSet fetched from Argopy for Indian Ocean region

### ISSUE THREAD

**Issue by mayursapkal** [euroargodev/argopy#87]
Hello, Argopy!
I began working on a classification problem in the beginning of this year, using Argo data as input.
Since the project is based on the Indian Ocean, I used Argopy's Parallel data fetching method to obtain data from 2010 to 2019, ranging from 0 to 1000 dbar.
Data was fetched every two years, and then I used Xarray to merge all of the files.
I had a lot of problems using that data because the data was not handled/stored correctly within in the array.
The Issues are;
1) Variables values not in sorted manner.
Eg. variables values (Pressure, Temp, Salinity) in most of the arrays started with from 500 dbar values and respective to those Temperature and salinity values also stored in arrays.
![Screenshot (92)_LI](https://user-images.githubusercontent.com/72465799/117495040-c5969c00-af92-11eb-8942-754f75f30dfe.jpg)

2) Pressure values starting with negative values.
![Screenshot (96)_LI](https://user-images.githubusercontent.com/72465799/117495174-e8c14b80-af92-11eb-8cc5-1a90eae478fa.jpg)

3) Only single value in whole DataArray.
![Screenshot (97)](https://user-images.githubusercontent.com/72465799/117495277-0bebfb00-af93-11eb-939f-a6117b35c37d.png)

4) Unsuited Values
![Screenshot (98)](https://user-images.githubusercontent.com/72465799/117495529-62f1d000-af93-11eb-9fd8-53020f758307.png)

5) Partial values for work, when fetched up to 1000 dbar level
![Screenshot (99)_LI](https://user-images.githubusercontent.com/72465799/117495802-bf54ef80-af93-11eb-99e2-ef5a5d06bf70.jpg)

**Comment by mayursapkal** [comment]
Hi @quai20,
Sorry for late reply. I've attached a screenshot of some of the Floats that have the above issue, and I tried to fix the problem on my own because I was short on time at the time of my project.[(link)](https://github.com/mayursapkal/Ocean-through-ML-s-Eye/blob/d3f24a9bd2b8171ac79774b9029c349041a8774a/Argo%20Data%20Prepration/Code/Data%20Prepration%202.0-Copy1.ipynb) .


1)  WMO float identifier : A9IIIII- 
![image](https://user-images.githubusercontent.com/72465799/117794760-2a8c1380-b26b-11eb-8310-dd5dbf4af8e7.png)
![image](https://user-images.githubusercontent.com/72465799/117795253-a1c1a780-b26b-11eb-978e-0a8fdd2cefda.png)

**Comment by gmaze** [comment]
Hi @mayursapkal 
Could you please show us the command used to fetch and process the data used in notebook linked to your previous message ?

1- I suspect this is due to the point2profile transformation
2- Using vertical-index averaging throughout all profiles in the notebooks will mix a lot of very different pressures and could explain the weird figures

**Comment by gmaze** [comment]
Closing because of a lack of information
