### ISSUE TITLE
Couldn't fetch data

### ISSUE THREAD

**Issue by lavanthaya** [euroargodev/argopy#88]
I was trying to go through the given steps to fetch data but it shows an error

#### MCVE Code Sample

```python
# Your code here
from argopy import DataFetcher as ArgoDataFetcher
ds = ArgoDataFetcher(src='erddap').region([-75, -45, 20, 30, 0, 100, '2011-01', '2011-02']).to_xarray()
```

#### Expected Output
<xarray.Dataset>

#### Problem Description

I tried in the given notebook and in my local server, but both pop up below error
---------------------------------------------------------------------------
ClientResponseError                       Traceback (most recent call last)
<ipython-input-2-342a12ae1e91> in <module>
----> 1 ds = ArgoDataFetcher(src='erddap').region([-75, -45, 20, 30, 0, 100, '2011-01', '2011-02']).to_xarray()

/srv/conda/envs/notebook/lib/python3.8/site-packages/argopy/fetchers.py in to_xarray(self, **kwargs)
    270             raise InvalidFetcher(" Initialize an access point (%s) first." %
    271                                  ",".join(self.Fetchers.keys()))
--> 272         xds = self.fetcher.to_xarray(**kwargs)
    273         xds = self.postproccessor(xds)
    274         return xds

/srv/conda/envs/notebook/lib/python3.8/site-packages/argopy/data_fetchers/erddap_data.py in to_xarray(self, errors)
    423         if not self.parallel:
    424             if len(self.uri) == 1:
--> 425                 ds = self.fs.open_dataset(self.uri[0])
    426             else:
    427                 ds = self.fs.open_mfdataset(

/srv/conda/envs/notebook/lib/python3.8/site-packages/argopy/stores/filesystems.py in open_dataset(self, url, *args, **kwargs)
    465         # with self.fs.open(url) as of:
    466         #     ds = xr.open_dataset(of, *args, **kwargs)
--> 467         data = self.fs.cat_file(url)
    468         ds = xr.open_dataset(data, *args, **kwargs)
    469         if "source" not in ds.encoding:

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
    116     def wrapper(*args, **kwargs):
    117         self = obj or args[0]
--> 118         return maybe_sync(func, self, *args, **kwargs)
    119 
    120     return wrapper

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in maybe_sync(func, self, *args, **kwargs)
     95         if inspect.iscoroutinefunction(func):
     96             # run the awaitable on the loop
---> 97             return sync(loop, func, *args, **kwargs)
     98         else:
     99             # just call the blocking function

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     66     if error[0]:
     67         typ, exc, tb = error[0]
---> 68         raise exc.with_traceback(tb)
     69     else:
     70         return result[0]

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in f()
     50             if callback_timeout is not None:
     51                 future = asyncio.wait_for(future, callback_timeout)
---> 52             result[0] = await future
     53         except Exception:
     54             error[0] = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/implementations/http.py in _cat_file(self, url, **kwargs)
    153             if r.status == 404:
    154                 raise FileNotFoundError(url)
--> 155             r.raise_for_status()
    156             out = await r.read()
    157         return out

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiohttp/client_reqrep.py in raise_for_status(self)
    939             assert self.reason is not None
    940             self.release()
--> 941             raise ClientResponseError(
    942                 self.request_info,
    943                 self.history,

ClientResponseError: 500, message='500', url=URL('https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude%3E=-75&longitude%3C=-45&latitude%3E=20&latitude%3C=30&pres%3E=0&pres%3C=100&time%3E=1293840000.0&time%3C=1296518400.0&distinct()&orderBy(%22time,pres%22)')

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 | packaged by conda-forge | (default, Jul 24 2020, 01:25:15) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.19.167+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

argopy: 0.1.7
xarray: 0.16.1
pandas: 1.2.0
numpy: 1.19.4
scipy: 1.5.3
fsspec: 0.8.3
erddapy: 0.7.2
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.4.0
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.8.4
iris: None
bottleneck: 1.3.2
dask: 2.30.0
distributed: 2.30.0
matplotlib: 3.3.2
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: None
gsw: 3.4.0
setuptools: 49.6.0.post20201009
pip: 20.2.3
conda: None
pytest: 6.1.1
IPython: 7.18.1
sphinx: None

</details>

**Comment by quai20** [comment]
Hi @lavanthaya 
The Argo Erddap server seems to be down, maybe that's the problem.
Can you try to run your request with argovis ? Or retry with erddap later ?
`ds = ArgoDataFetcher(src='argovis').region([-75, -45, 20, 30, 0, 100, '2011-01', '2011-02']).to_xarray()`

**Comment by lavanthaya** [comment]
Hi @quai20 
Seems you are correct, some server issue.
Now it's working, 
Thank you for your responce
