### ISSUE TITLE
Error using argopy for the first time

### ISSUE THREAD

**Issue by PedroVelez** [euroargodev/argopy#9]
Hi, I installed the argopy using 
```
pip install git+http://github.com/euroargodev/argopy.git@master
```

However initializing the DataFetcher gives me an error:

```
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from argopy import DataFetcher as ArgoDataFetcher
/Users/pvb/miniconda3/lib/python3.7/site-packages/argopy/fetchers.py:48: UserWarning: An error occured while loading the ERDDAP data fetcher, it will not be available !
<class 'ModuleNotFoundError'>
  warnings.warn("An error occured while loading the ERDDAP data fetcher, it will not be available !\n%s" % e)
```

```
>>> argo_loader = ArgoDataFetcher()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/argopy/fetchers.py", line 96, in __init__
    raise ValueError("The %s data fetcher is not available" % backend)
ValueError: The erddap data fetcher is not available
```

I am using a mac book pro with Kernel Version 19.3.0 (Catalina, although it should not be this the problem since I am even able to use dask to analyse model data, ... ), and I have installed conda with homebrew and pip from conda.  Installing miniconda directly and then using pip give the same result.

Any help?
thanks a lot
Pedro

**Comment by gmaze** [comment]
Hi @PedroVelez 
This is probably coming from the fact that you don't have [ERDDAPY](https://github.com/ioos/erddapy) installed. This is a library used by argopy to manage request to the erddap server.

Since erddap is the default backend for data fetching, ERDDAPY must be a package requirement. This is a bug that is now fixed (commit 73dd5006c575f75c568d04b88a241e8bb170709f).

Can you please try to reinstall argopy now ? a try again an example ?

**Comment by PedroVelez** [comment]
Thanks @gmaze . Reinstalled argopy and now it installs ERDDAPY, however I can not retrieve a float:

```
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from argopy import DataFetcher as ArgoDataFetcher
>>> argo_loader = ArgoDataFetcher()
>>> argo_loader = ArgoDataFetcher(backend='erddap')
>>> argo_loader = ArgoDataFetcher(cachedir='tmp')
>>> argo_loader.profile(6902746, 34).to_xarray()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/argopy/fetchers.py", line 179, in to_xarray
    xds = self.fetcher.to_xarray(**kwargs)
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/argopy/data_fetchers/erddap.py", line 378, in to_xarray
    ds.to_netcdf(self.cachepath)
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/xarray/core/dataset.py", line 1545, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/xarray/backends/api.py", line 1051, in to_netcdf
    scheduler = _get_scheduler()
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/xarray/backends/locks.py", line 79, in _get_scheduler
    actual_get = dask.base.get_scheduler(get, collection)
AttributeError: module 'dask' has no attribute 'base'
```

**Comment by gmaze** [comment]
Ok, so now this is dask / xarray versions issue.

What's your xarray version ? You probably use a too older version that calls on a deprecated property of dask.

I updated argopy requirements to more recent versions.

Can you try again an ``argopy`` installation and dump all your versions:
```python
import dask, xarray
print('dask',dask.__version__, 'xarray',xarray.__version__)
```

**Comment by PedroVelez** [comment]
Thanks. 
I have reinstalled argopy and also tried to update manuall dask and xarray, in both cases I got the same version:

´´´
$>>python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask, xarray
print('dask',dask.__version__, 'xarray',xarray.__version__)
>>> print('dask',dask.__version__, 'xarray',xarray.__version__)
dask 2.12.0 xarray 0.15.0
>>> 
´´´

and after the same error for the data fetcher:

```
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from argopy import DataFetcher as ArgoDataFetcher
>>> argo_loader = ArgoDataFetcher()
>>> argo_loader = ArgoDataFetcher(backend='erddap')
>>> argo_loader = ArgoDataFetcher(cachedir='tmp')
>>> argo_loader.profile(6902746, 34).to_xarray()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/argopy/fetchers.py", line 179, in to_xarray
    xds = self.fetcher.to_xarray(**kwargs)
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/argopy/data_fetchers/erddap.py", line 378, in to_xarray
    ds.to_netcdf(self.cachepath)
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/xarray/core/dataset.py", line 1545, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/xarray/backends/api.py", line 1051, in to_netcdf
    scheduler = _get_scheduler()
  File "/Users/pvb/miniconda3/lib/python3.7/site-packages/xarray/backends/locks.py", line 79, in _get_scheduler
    actual_get = dask.base.get_scheduler(get, collection)
AttributeError: module 'dask' has no attribute 'base'
```

**Comment by quai20** [comment]
On my side it works (installed just now) with these versions : 
```
import dask, xarray
print('dask',dask.__version__, 'xarray',xarray.__version__)
**dask 2.1.0 xarray 0.15.0**

```

**Comment by PedroVelez** [comment]
downgraded dask to the same version as @quai20 

```
 import dask, xarray
>>> print('dask',dask.__version__, 'xarray',xarray.__version__)
dask 2.1.0 xarray 0.15.0

but I still get the same error:
````
AttributeError: module 'dask' has no attribute 'base'
````

````
but i get the same error

**Comment by quai20** [comment]
Hi @PedroVelez ,
did you restart the kernel/notebook after upgrading/downgrading ?
If we have the same version of dask, I don't understand why the attribute is not found...

**Comment by PedroVelez** [comment]
Yes, however installing manually all the requirements: 
```
pip install scipy xarray scikit-learn ipython numpydoc dask toolz erddapy
````
works!!

**Comment by gmaze** [comment]
ok, so this may have been due to updating path and versions loaded by the kernel.
Glad it works !

**Comment by Weidong-Li-HydroMet** [comment]
Hi! I'm getting a TimeoutError while trying the example code from the argopy documentation (attempting to fetch Argo float data for 75°W-45°W, 20°N-30°N, 0-10m depth, Jan-Jun 2011). Has anyone encountered this issue and found a solution? Thanks!
<img width="831" alt="image" src="https://github.com/user-attachments/assets/a1a9570d-c61c-46fd-911c-42336282c638" />

**Comment by gmaze** [comment]
Hi @Weidong-Li-HydroMet 
when you encounter a timeout error, you can:
- wait and try again later (the request works for me a few minutes ago)
- check for your data source availability (``argopy.status()`` or https://argopy.statuspage.io/)
- change data source
